In [1]:
# Import packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
import statistics

## Part I Crashes Data (2019)

In [267]:
# Load the dataset for 2019
crash19_raw = pd.read_csv('Ped_crash\Crashes_Ped_2018.csv')

In [52]:
# # Load the dataset for 2012
# crash19_raw = pd.read_csv('Crashes_12.csv')

In [268]:
# Visualize the unique # of cities
crash19_raw.CITY.nunique()

81

In [269]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(crash19_raw.CITY.value_counts())

CITY
LOS ANGELES             3215
UNINCORPORATED           394
LONG BEACH               331
POMONA                    84
SANTA MONICA              84
GLENDALE                  78
PASADENA                  75
INGLEWOOD                 58
ALHAMBRA                  57
WEST HOLLYWOOD            56
LANCASTER                 51
TORRANCE                  47
COMPTON                   43
BEVERLY HILLS             43
DOWNEY                    42
EL MONTE                  42
CULVER CITY               37
PALMDALE                  35
MONTEREY PARK             35
SOUTH GATE                33
NORWALK                   32
GARDENA                   31
BELLFLOWER                31
LAKEWOOD                  31
HUNTINGTON PARK           30
WHITTIER                  30
WEST COVINA               29
CARSON                    27
MONTEBELLO                27
REDONDO BEACH             26
HAWTHORNE                 26
ARCADIA                   25
SANTA CLARITA             25
BALDWIN PARK              24
BELL                      24
ROSEMEAD                  21
LYNWOOD                   20
PICO RIVERA               19
BELL GARDENS              19
PARAMOUNT                 18
SAN GABRIEL               15
AZUSA                     14
MANHATTAN BEACH           13
MALIBU                    12
EL SEGUNDO                12
GLENDORA                  12
CERRITOS                  12
CLAREMONT                 11
CUDAHY                    11
LA MIRADA                 10
COVINA                    10
DIAMOND BAR               10
SANTA FE SPRINGS           9
HAWAIIAN GARDENS           8
MONROVIA                   8
SIGNAL HILL                8
SAN DIMAS                  8
COMMERCE                   8
LA PUENTE                  7
LA VERNE                   7
SOUTH EL MONTE             6
VERNON                     6
HERMOSA BEACH              6
LAWNDALE                   6
SAN FERNANDO               6
TEMPLE CITY                6
MAYWOOD                    5
INDUSTRY                   5
ARTESIA                    5
CALABASAS                  4
DUARTE                     4
LA CANADA-FLINTRIDGE       4
AGOURA HILLS               4
SOUTH PASADENA             4
IRWINDALE                  3
SAN MARINO                 3
WALNUT                     2
HIDDEN HILLS               2
BURBANK                    2
PALOS VERDES EST           1
SIERRA MADRE               1
Name: count, dtype: int64

In [270]:
# Create the pedestrian crashes dataframe with data

crash19 = pd.DataFrame(crash19_raw.CITY.value_counts())
crash19

                  count
CITY
LOS ANGELES        3215
UNINCORPORATED      394
LONG BEACH          331
POMONA               84
SANTA MONICA         84
...                 ...
WALNUT                2
HIDDEN HILLS          2
BURBANK               2
PALOS VERDES EST      1
SIERRA MADRE          1

[81 rows x 1 columns]

In [271]:
# Transpose and make lowercase

crash19 = crash19.transpose()
crash19.columns = map(str.lower, crash19.columns)
crash19

,los angeles,unincorporated,long beach,pomona,santa monica,glendale,pasadena,inglewood,alhambra,west hollywood,lancaster,torrance,compton,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,whittier,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,san fernando,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre
count,3215,394,331,84,84,78,75,58,57,56,51,47,43,43,42,42,37,35,35,33,32,31,31,31,30,30,29,27,27,26,26,25,25,24,24,21,20,19,19,18,15,14,13,12,12,12,12,11,11,10,10,10,9,8,8,8,8,8,7,7,6,6,6,6,6,6,5,5,5,4,4,4,4,4,3,3,2,2,2,1,1

## Part II ACS DATA

In [8]:
# # Load the dataset for ACS-5 year circa 2018

# ACS = pd.read_excel('ACS5Y_SChar_2018.xlsx', sheet_name = "Data")

In [272]:
# Load the dataset for ACS-5 year circa 2019

ACS = pd.read_excel('ACS_Data\ACS5Y_SChar_2018.xlsx', sheet_name = "Data")

In [82]:
# # Load the dataset for ACS-5 year circa 2012

# ACS = pd.read_excel('ACS5Y_SChar_2012.xlsx', sheet_name = "Data")

In [273]:
ACS

,Unnamed: 0,"Los Angeles County, California",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,"Agoura Hills-Malibu CCD, Los Angeles County, California",Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,"Compton CCD, Los Angeles County, California",Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,"Downey-Norwalk CCD, Los Angeles County, California",Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,"East San Gabriel Valley CCD, Los Angeles County, California",Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,"Inglewood CCD, Los Angeles County, California",Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,"Long Beach-Lakewood CCD, Los Angeles County, California",Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,"Los Angeles CCD, Los Angeles County, California",Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,"Newhall CCD, Los Angeles County, California",Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,"North Antelope Valley CCD, Los Angeles County, California",Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,"Palos Verdes CCD, Los Angeles County, California",Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,"Pasadena CCD, Los Angeles County, California",Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,"San Fernando Valley CCD, Los Angeles County, California",Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,"Santa Monica CCD, Los Angeles County, California",Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,"South Antelope Valley CCD, Los Angeles County, California",Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,"South Bay Cities CCD, Los Angeles County, California",Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,"South Gate-East Los Angeles CCD, Los Angeles County, California",Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,"Southwest San Gabriel Valley CCD, Los Angeles County, California",Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,"Torrance CCD, Los Angeles County, California",Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,"Upper San Gabriel Valley CCD, Los Angeles County, California",Unnamed: 154,Unnamed: 155,Unnamed: 156,Unnamed: 157,Unnamed: 158,Unnamed: 159,Unnamed: 160,"Whittier CCD, Los Angeles County, California",Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168
0,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN
1,Label,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error
2,Total population,"10,098,052",*****,"5,182,177","Â±12,058","1,341,455","Â±8,595","117,464","Â±2,494","64,932",Â±895,"32,098","Â±1,160","20,007","Â±1,124","1,125",Â±254,"351,459","Â±1,736","200,548","Â±2,502","29,382","Â±1,051","4,905",Â±681,"419,001",Â±471,"235,247","Â±2,364","28,791","Â±1,177","5,523",Â±584,"958,160","Â±3,225","534,188","Â±3,971","81,858","Â±2,128","9,492",Â±813,"374,562","Â±2,262","204,644","Â±2,919","44,617","Â±1,449","3,777",Â±470,"577,138",Â±271,"342,293","Â±2,687","81,510","Â±2,123","7,742",Â±666,"2,598,846","Â±6,065","1,194,520","Â±6,729","438,745","Â±4,675","29,914","Â±1,276","261,333","Â±1,577","155,988","Â±1,836","46,916","Â±1,507","3,024",Â±399,"192,039","Â±1,638","142,497","Â±1,995","27,425","Â±1,198","1,770",Â±329,"92,404",Â±399,"47,946","Â±1,188","20,341",Â±966,"1,619",Â±298,"274,554","Â±1,647","138,634","Â±2,247","53,842","Â±1,650","3,356",Â±449,"1,860,414","Â±5,963","838,715","Â±6,361","263,864","Â±3,494","24,607","Â±1,355","92,078",Â±38,"37,118","Â±1,371","31,740","Â±1,256","1,643",Â±350,"215,283","Â±1,924","135,182","Â±2,263","26,793","Â±1,201","2,104",Â±350,"139,773",Â±44,"72,916","Â±1,394","43,031","Â±1,286","2,055",Â±334,"497,962","Â±2,639","268,708","Â±3,047","12,186",Â±858,"3,324",Â±430,"323,808","Â±1,171","145,724","Â±2,390","14,436",Â±877,"2,864",Â±409,"146,392",Â±65,"75,012","Â±1,799","25,832","Â±1,288","2,146",Â±443,"332,369","Â±1,273","161,246","Â±2,192","23,796",Â±926,"3,801",Â±540,"325,545","Â±2,020","218,953","Â±2,266","26,343","Â±1,113","2,673",Â±371
3,AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Under 5 years,6.2%,*****,11.3%,Â±0.1,1.1%,Â±0.1,6.2%,Â±0.5,3.4%,Â±0.6,6.3%,Â±1.2,0.7%,Â±0.7,4.3%,Â±4.6,7.1%,Â±0.3,11.9%,Â±0.6,1.0%,Â±0.4,8.1%,Â±3.4,6.3%,Â±0.3,10.9%,Â±0.5,1.3%,Â±0.5,4.8%,Â±1.8,6.1%,Â±0.2,10.3%,Â±0.3,1.5%,Â±0.3,7.7%,Â±2.0,7.2%,Â±0.3,12.7%,Â±0.6,1.1%,Â±0.5,3.6%,Â±2.2,6.7%,Â±0.3,10.8%,Â±0.4,1.1%,Â±0.3,5.2%,Â±1.8,6.0%,Â±0.1,12.2%,Â±0.2,0.9%,Â±0.1,5.4%,Â±1.1,6.5%,Â±0.4,10.3%,Â±0.6,1.3%,Â±0.3,3.6%,Â±2.3,7.6%,Â±0.5,9.8%,Â±0.7,1.3%,Â±0.5,4.0%,Â±3.0,4.2%,Â±0.4,7.4%,Â±0.9,0.7%,Â±0.4,4.0%,Â±4.8,6.0%,Â±0.3,11.0%,Â±0.6,0.9%,Â±0.3,7.0%,Â±3.4,5.8%,Â±0.1,11.8%,Â±0.2,1.2%,Â±0.2,8.0%,Â±1.4,4.7%,Â±0.5,10.8%,Â±1.3,0.5%,Â±0.3,2.4%,Â±2.7,7.6%,Â±0.5,11.5%,Â±0.7,1.8%,Â±0.7,6.5%,Â±3.6,6.3%,Â±0.6,11.0%,Â±1.0,1.6%,Â±0.5,1.6%,Â±1.4,7.5%,Â±0.2,13.2%,Â±0.4,3.7%,Â±1.0,9.7%,Â±3.3,5.6%,Â±0.3,11.7%,Â±0.6,1.3%,Â±0.7,8.9%,Â±3.6,6.1%,Â±0.5,10.4%,Â±0.7,1.9%,Â±0.7,2.5%,Â±2.5,5.6%,Â±0.3,10.7%,Â±0.5,1.7%,Â±0.6,3.9%,Â±1.6,6.0%,Â±0.3,8.6%,Â±0.4,1.4%,Â±0.7,7.8%,Â±2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,100 to 149 percent of the poverty level,10.7%,Â±0.1,10.3%,Â±0.2,6.2%,Â±0.2,8.5%,Â±0.7,3.1%,Â±0.8,3.2%,Â±1.1,2.4%,Â±1.0,6.2%,Â±4.1,13.2%,Â±0.8,13.6%,Â±0.9,9.3%,Â±1.1,14.1%,Â±4.7,10.2%,Â±0.6,9.8%,Â±0.8,8.8%,Â±1.0,9.0%,Â±3.0,9.5%,Â±0.4,9.1%,Â±0.5,6.9%,Â±0.8,8.0%,Â±2.6,13.0%,Â±0.8,13.1%,Â±1.0,8.5%,Â±1.1,9.8%,Â±4.6,10.1%,Â±0.6,9.5%,Â±0.6,7.0%,Â±0.7,8.5%,Â±2.4,11.9%,Â±0.3,11.9%,Â±0.4,6.4%,Â±0.3,9.1%,Â±1.3,5.1%,Â±0.6,4.7%,Â±0.6,3.4%,Â±0.6,4.2%,Â±4.4,10.7%,Â±1.1,11.3%,Â±1.4,8.6%,Â±1.7,9.8%,Â±5.7,3.0%,Â±0.8,3.2%,Â±1.0,2.4%,Â±1.2,6.0%,Â±5.8,6.7%,Â±0.6,5.9%,Â±0.7,5.2%,Â±0.7,5.7%,Â±3.3,10.0%,Â±0.3,9.4%,Â±0.4,5.6%,Â±0.4,8.2%,Â±1.5,5.9%,Â±0.9,5.7%,Â±1.2,4.8%,Â±1.2,8.7%,Â±7.9,12.3%,Â±1.2,12.3%,Â±1.3,9.0%,Â±1.5,12.3%,Â±7.0,2.8%,Â±0.6,2.7%,Â±0.8,2.4%,Â±0.6,1.8%,Â±2.3,16.8%,Â±0.6,16.4%,Â±0.8,13.3%,Â±2.5,10.6%,Â±3.7,13.8%,Â±0.9,12.0%,Â±1.0,9.2%,Â±1.5,11.0%,Â±5.2,4.9%,Â±0.7,3.9%,Â±0.7,4.9%,Â±1.1,2.9%,Â±2.9,11.1%,Â±0.7,10.7%,Â±0.9,6.0%,Â±1.4,8.8%,Â±4.1,8.8%,Â±0.6,8.2%,Â±0.7,6.1%,Â±1.1,6.0%,Â±2.9
60,At or above 150 percent of the poverty level,73.3%,Â±0.2,73.3%,Â±0.3,82.8%,Â±0.3,79.8%,Â±1.0,90.6%,Â±1.4,90.3%,Â±1.9,91.5%,Â±1.9,84.6%,Â±7.2,68.8%,Â±1.0,66.4%,Â±1.1,74.4%,Â±2.1,74.3%,Â±5.6,77.9%,Â±0.9,78.3%,Â±1.0,79.2%,Â±1.6,80.7%,Â±4.3,78.7%,Â±0.6,79.2%,Â±0.7,84.5%,Â±1.0,82.7%,Â±3.2,69.3%,Â±0.9,68.6%,Â±1.2,77.2%,Â±1.8,78.2%,Â±5.2,73.5%,Â±0.7,73.7%,Â±0.9,81.6%,Â±0.9,77.8%,Â±3.9,66.9%,Â±0.3,65.3%,Â±0.5,80.0%,Â±0.5,75.8%,Â±1.9,86.8%,Â±1.0,87.1%,Â±1.1,91.6%,Â±0.9,91.6%,Â±4.7,66.0%,Â±1.3,62.8%,Â±1.6,76.5%,Â±2.4,77.6%,Â±8.1,90.4%,Â±1.2,90.8%,Â±1.4,91.5%,Â±1.7,89.7%,Â±6.7,81.6%,Â±0.9,83.4%,Â±1.1,86.7%,Â±1.1,84.9%,Â±5.7,75.7%,Â±0.4,76.3%,Â±0.5,84.4%,Â±0.6,81.2%,Â±2.2,83.7%,Â±1.2,84.9%,Â±1.7,86.8%,Â±1.8,76.9%,Â±9.5,71.4%,Â±1.4,70.4%,Â±1.7,79.0%,Â±2.0,76.3%,Â±8.4,92.5%,Â±0.8,92.8%,Â±1.0,92.9%,Â±1.1,93.0%,Â±3.4,59.8%,Â±0.8,59.0%,Â±0.9,63.3%,Â±3.6,70.4%,Â±6.6,72.5%,Â±1.0,76.0%,Â±1.2,79.3%,Â±2.6,78.1%,Â±6.3,88.1%,Â±1.1,89.7%,Â±1.2,90.1%,Â±1.5,89.9%,Â±6.0,74.6%,Â±0.9,74.3%,Â±1.1,86.0%,Â±1.7,81.4%,Â±5.4,81.4%,Â±0.9,82.2%,Â±1.0,84.8%,Â±1.7,87.4%,Â±4.1
61,PERCENT ALLOCATED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Citizenship status,7.5%,(X),(X),(X),(X),(X),(X),(X),6.7%,(X),(X),(X),(X),(X),(X),(X),10.5%,(X),(X),(X),(X),(X),(X),(X),7.9%,(X),(X),(X),(X),(X),(X),(X),7.5%,(X),(X),(X),(X),(X),(X),(X),6.7%,(X),(X),(X),(X),(X),(X),(X),7.4%,(X),(X),(X),(X),(X),(X),(X),6.5%,(X),(X),(X),(X),(X),(X),(X),6.8%,(X),(X),(X),(X),(X),(X),(X),5.2%,(X),(X),(X),(X),(X),(X),(X),5.3%,(X),(X),(X),(X),(X),(X),(X),6.1%,(X),(X),(X),(X),(X),(X),(X),10.6%,(X),(X),(X),(X),(X),(X),(X),5.6%,(X),(X),(X),(X),(X),(X),(X),6.0%,(X),(X),(X),(X),(X),(X),(X),6.2%,(X),(X),(X),(X),(X),(X),(X),6.3%,(X),(X),(X),(X),(X),(X),(X),6.6%,(X),(X),(X),(X),(X),(X),(X),5.5%,(X),(X),(X),(X),(X),(X),(X),6.4%,(X),(X),(X),(X),(X),(X),(X),6.9%,(X),(X),(X),(X),(X),(X),(X)
63,Place of birth,9.4%,(X),(X),(X),(X),(X),(X),(X),10.6%,(X),(X),(X),(X),(X),(X),(X),11.9%,(X),(X),(X),(X),(X),(X),(X),9.3%,(X),(X),(X),(X),(X),(X),(X),9.1%,(X),(X),(X),(X),(X),(X),(X),8.3%,(X),(X),(X),(X),(X),(X),(X),9.2%,(X),(X),(X),(X),(X),(X),(X),8.4%,(X),(X),(X),(X),(X),(X),(X),9.1%,(X),(X),(X),(X),(X),(X),(X),8.3%,(X),(X),(X),(X),(X),(X),(X),8.4%,(X),(X),(X),(X),(X),(X),(X),9.5%,(X),(X),(X),(X),(X),(X),(X),12.4%,(X),(X),(X),(X),(X),(X),(X),8.6%,(X),(X),(X),(X),(X),(X),(X),8.8%,(X),(X),(X),(X),(X),(X),(X),9.1%,(X),(X),(X),(X),(X),(X),(X),6.7%,(X),(X),(X),(X),(X),(X),(X),8.1%,(X),(X),(X),(X),(X),(X),(X),8.2%,(X),(X),(X),(X),(X),(X),(X),8.0%,(X),(X),(X),(X),(X),(X),(X),8.8%,(X),(X),(X),(X),(X),(X),(X)

In [64]:
# Locate the different cities

ACS.iloc[:,1]

0         Total
1      Estimate
2     9,974,203
3           NaN
4          6.5%
        ...
59        12.0%
60        69.6%
61          NaN
62         4.7%
63         7.1%
Name: Los Angeles County, California, Length: 64, dtype: object

In [65]:
ACS.iloc[:,9]

0        Total
1     Estimate
2       65,420
3          NaN
4         4.5%
        ...
59        2.8%
60       89.2%
61         NaN
62        3.8%
63       10.5%
Name: Agoura Hills-Malibu CCD, Los Angeles County, California, Length: 64, dtype: object

In [66]:
ACS.iloc[:,17]

0        Total
1     Estimate
2      345,211
3          NaN
4         7.8%
        ...
59       15.0%
60       64.0%
61         NaN
62        7.7%
63        9.6%
Name: Compton CCD, Los Angeles County, California, Length: 64, dtype: object

In [274]:
# Rename the row index to "key" and set first column to row names/index

ACS_mod = ACS.rename(columns={ACS.columns[0]: "key"})
ACS_mod = ACS_mod.set_index(ACS_mod.columns[0])
#ACS_mod = ACS.drop(ACS.columns[0], axis=1)
ACS_mod

,"Los Angeles County, California",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,"Agoura Hills-Malibu CCD, Los Angeles County, California",Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,"Compton CCD, Los Angeles County, California",Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,"Downey-Norwalk CCD, Los Angeles County, California",Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,"East San Gabriel Valley CCD, Los Angeles County, California",Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,"Inglewood CCD, Los Angeles County, California",Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,"Long Beach-Lakewood CCD, Los Angeles County, California",Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,"Los Angeles CCD, Los Angeles County, California",Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,"Newhall CCD, Los Angeles County, California",Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,"North Antelope Valley CCD, Los Angeles County, California",Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,"Palos Verdes CCD, Los Angeles County, California",Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,"Pasadena CCD, Los Angeles County, California",Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,"San Fernando Valley CCD, Los Angeles County, California",Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,"Santa Monica CCD, Los Angeles County, California",Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,"South Antelope Valley CCD, Los Angeles County, California",Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,"South Bay Cities CCD, Los Angeles County, California",Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,"South Gate-East Los Angeles CCD, Los Angeles County, California",Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,"Southwest San Gabriel Valley CCD, Los Angeles County, California",Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,"Torrance CCD, Los Angeles County, California",Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,"Upper San Gabriel Valley CCD, Los Angeles County, California",Unnamed: 154,Unnamed: 155,Unnamed: 156,Unnamed: 157,Unnamed: 158,Unnamed: 159,Unnamed: 160,"Whittier CCD, Los Angeles County, California",Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168
key,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN,Total,NaN,Native; born in state of residence,NaN,Native; born in other state in the U.S.,NaN,Native; born outside U.S.,NaN
Label,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error
Total population,"10,098,052",*****,"5,182,177","Â±12,058","1,341,455","Â±8,595","117,464","Â±2,494","64,932",Â±895,"32,098","Â±1,160","20,007","Â±1,124","1,125",Â±254,"351,459","Â±1,736","200,548","Â±2,502","29,382","Â±1,051","4,905",Â±681,"419,001",Â±471,"235,247","Â±2,364","28,791","Â±1,177","5,523",Â±584,"958,160","Â±3,225","534,188","Â±3,971","81,858","Â±2,128","9,492",Â±813,"374,562","Â±2,262","204,644","Â±2,919","44,617","Â±1,449","3,777",Â±470,"577,138",Â±271,"342,293","Â±2,687","81,510","Â±2,123","7,742",Â±666,"2,598,846","Â±6,065","1,194,520","Â±6,729","438,745","Â±4,675","29,914","Â±1,276","261,333","Â±1,577","155,988","Â±1,836","46,916","Â±1,507","3,024",Â±399,"192,039","Â±1,638","142,497","Â±1,995","27,425","Â±1,198","1,770",Â±329,"92,404",Â±399,"47,946","Â±1,188","20,341",Â±966,"1,619",Â±298,"274,554","Â±1,647","138,634","Â±2,247","53,842","Â±1,650","3,356",Â±449,"1,860,414","Â±5,963","838,715","Â±6,361","263,864","Â±3,494","24,607","Â±1,355","92,078",Â±38,"37,118","Â±1,371","31,740","Â±1,256","1,643",Â±350,"215,283","Â±1,924","135,182","Â±2,263","26,793","Â±1,201","2,104",Â±350,"139,773",Â±44,"72,916","Â±1,394","43,031","Â±1,286","2,055",Â±334,"497,962","Â±2,639","268,708","Â±3,047","12,186",Â±858,"3,324",Â±430,"323,808","Â±1,171","145,724","Â±2,390","14,436",Â±877,"2,864",Â±409,"146,392",Â±65,"75,012","Â±1,799","25,832","Â±1,288","2,146",Â±443,"332,369","Â±1,273","161,246","Â±2,192","23,796",Â±926,"3,801",Â±540,"325,545","Â±2,020","218,953","Â±2,266","26,343","Â±1,113","2,673",Â±371
AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Under 5 years,6.2%,*****,11.3%,Â±0.1,1.1%,Â±0.1,6.2%,Â±0.5,3.4%,Â±0.6,6.3%,Â±1.2,0.7%,Â±0.7,4.3%,Â±4.6,7.1%,Â±0.3,11.9%,Â±0.6,1.0%,Â±0.4,8.1%,Â±3.4,6.3%,Â±0.3,10.9%,Â±0.5,1.3%,Â±0.5,4.8%,Â±1.8,6.1%,Â±0.2,10.3%,Â±0.3,1.5%,Â±0.3,7.7%,Â±2.0,7.2%,Â±0.3,12.7%,Â±0.6,1.1%,Â±0.5,3.6%,Â±2.2,6.7%,Â±0.3,10.8%,Â±0.4,1.1%,Â±0.3,5.2%,Â±1.8,6.0%,Â±0.1,12.2%,Â±0.2,0.9%,Â±0.1,5.4%,Â±1.1,6.5%,Â±0.4,10.3%,Â±0.6,1.3%,Â±0.3,3.6%,Â±2.3,7.6%,Â±0.5,9.8%,Â±0.7,1.3%,Â±0.5,4.0%,Â±3.0,4.2%,Â±0.4,7.4%,Â±0.9,0.7%,Â±0.4,4.0%,Â±4.8,6.0%,Â±0.3,11.0%,Â±0.6,0.9%,Â±0.3,7.0%,Â±3.4,5.8%,Â±0.1,11.8%,Â±0.2,1.2%,Â±0.2,8.0%,Â±1.4,4.7%,Â±0.5,10.8%,Â±1.3,0.5%,Â±0.3,2.4%,Â±2.7,7.6%,Â±0.5,11.5%,Â±0.7,1.8%,Â±0.7,6.5%,Â±3.6,6.3%,Â±0.6,11.0%,Â±1.0,1.6%,Â±0.5,1.6%,Â±1.4,7.5%,Â±0.2,13.2%,Â±0.4,3.7%,Â±1.0,9.7%,Â±3.3,5.6%,Â±0.3,11.7%,Â±0.6,1.3%,Â±0.7,8.9%,Â±3.6,6.1%,Â±0.5,10.4%,Â±0.7,1.9%,Â±0.7,2.5%,Â±2.5,5.6%,Â±0.3,10.7%,Â±0.5,1.7%,Â±0.6,3.9%,Â±1.6,6.0%,Â±0.3,8.6%,Â±0.4,1.4%,Â±0.7,7.8%,Â±2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100 to 149 percent of the poverty level,10.7%,Â±0.1,10.3%,Â±0.2,6.2%,Â±0.2,8.5%,Â±0.7,3.1%,Â±0.8,3.2%,Â±1.1,2.4%,Â±1.0,6.2%,Â±4.1,13.2%,Â±0.8,13.6%,Â±0.9,9.3%,Â±1.1,14.1%,Â±4.7,10.2%,Â±0.6,9.8%,Â±0.8,8.8%,Â±1.0,9.0%,Â±3.0,9.5%,Â±0.4,9.1%,Â±0.5,6.9%,Â±0.8,8.0%,Â±2.6,13.0%,Â±0.8,13.1%,Â±1.0,8.5%,Â±1.1,9.8%,Â±4.6,10.1%,Â±0.6,9.5%,Â±0.6,7.0%,Â±0.7,8.5%,Â±2.4,11.9%,Â±0.3,11.9%,Â±0.4,6.4%,Â±0.3,9.1%,Â±1.3,5.1%,Â±0.6,4.7%,Â±0.6,3.4%,Â±0.6,4.2%,Â±4.4,10.7%,Â±1.1,11.3%,Â±1.4,8.6%,Â±1.7,9.8%,Â±5.7,3.0%,Â±0.8,3.2%,Â±1.0,2.4%,Â±1.2,6.0%,Â±5.8,6.7%,Â±0.6,5.9%,Â±0.7,5.2%,Â±0.7,5.7%,Â±3.3,10.0%,Â±0.3,9.4%,Â±0.4,5.6%,Â±0.4,8.2%,Â±1.5,5.9%,Â±0.9,5.7%,Â±1.2,4.8%,Â±1.2,8.7%,Â±7.9,12.3%,Â±1.2,12.3%,Â±1.3,9.0%,Â±1.5,12.3%,Â±7.0,2.8%,Â±0.6,2.7%,Â±0.8,2.4%,Â±0.6,1.8%,Â±2.3,16.8%,Â±0.6,16.4%,Â±0.8,13.3%,Â±2.5,10.6%,Â±3.7,13.8%,Â±0.9,12.0%,Â±1.0,9.2%,Â±1.5,11.0%,Â±5.2,4.9%,Â±0.7,3.9%,Â±0.7,4.9%,Â±1.1,2.9%,Â±2.9,11.1%,Â±0.7,10.7%,Â±0.9,6.0%,Â±1.4,8.8%,Â±4.1,8.8%,Â±0.6,8.2%,Â±0.7,6.1%,Â±1.1,6.0%,Â±2.9
At or above 150 percent of the poverty level,73.3%,Â±0.2,73.3%,Â±0.3,82.8%,Â±0.3,79.8%,Â±1.0,90.6%,Â±1.4,90.3%,Â±1.9,91.5%,Â±1.9,84.6%,Â±7.2,68.8%,Â±1.0,66.4%,Â±1.1,74.4%,Â±2.1,74.3%,Â±5.6,77.9%,Â±0.9,78.3%,Â±1.0,79.2%,Â±1.6,80.7%,Â±4.3,78.7%,Â±0.6,79.2%,Â±0.7,84.5%,Â±1.0,82.7%,Â±3.2,69.3%,Â±0.9,68.6%,Â±1.2,77.2%,Â±1.8,78.2%,Â±5.2,73.5%,Â±0.7,73.7%,Â±0.9,81.6%,Â±0.9,77.8%,Â±3.9,66.9%,Â±0.3,65.3%,Â±0.5,80.0%,Â±0.5,75.8%,Â±1.9,86.8%,Â±1.0,87.1%,Â±1.1,91.6%,Â±0.9,91.6%,Â±4.7,66.0%,Â±1.3,62.8%,Â±1.6,76.5%,Â±2.4,77.6%,Â±8.1,90.4%,Â±1.2,90.8%,Â±1.4,91.5%,Â±1.7,89.7%,Â±6.7,81.6%,Â±0.9,83.4%,Â±1.1,86.7%,Â±1.1,84.9%,Â±5.7,75.7%,Â±0.4,76.3%,Â±0.5,84.4%,Â±0.6,81.2%,Â±2.2,83.7%,Â±1.2,84.9%,Â±1.7,86.8%,Â±1.8,76.9%,Â±9.5,71.4%,Â±1.4,70.4%,Â±1.7,79.0%,Â±2.0,76.3%,Â±8.4,92.5%,Â±0.8,92.8%,Â±1.0,92.9%,Â±1.1,93.0%,Â±3.4,59.8%,Â±0.8,59.0%,Â±0.9,63.3%,Â±3.6,70.4%,Â±6.6,72.5%,Â±1.0,76.0%,Â±1.2,79.3%,Â±2.6,78.1%,Â±6.3,88.1%,Â±1.1,89.7%,Â±1.2,90.1%,Â±1.5,89.9%,Â±6.0,74.6%,Â±0.9,74.3%,Â±1.1,86.0%,Â±1.7,81.4%,Â±5.4,81.4%,Â±0.9,82.2%,Â±1.0,84.8%,Â±1.7,87.4%,Â±4.1
PERCENT ALLOCATED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Citizenship status,7.5%,(X),(X),(X),(X),(X),(X),(X),6.7%,(X),(X),(X),(X),(X),(X),(X),10.5%,(X),(X),(X),(X),(X),(X),(X),7.9%,(X),(X),(X),(X),(X),(X),(X),7.5%,(X),(X),(X),(X),(X),(X),(X),6.7%,(X),(X),(X),(X),(X),(X),(X),7.4%,(X),(X),(X),(X),(X),(X),(X),6.5%,(X),(X),(X),(X),(X),(X),(X),6.8%,(X),(X),(X),(X),(X),(X),(X),5.2%,(X),(X),(X),(X),(X),(X),(X),5.3%,(X),(X),(X),(X),(X),(X),(X),6.1%,(X),(X),(X),(X),(X),(X),(X),10.6%,(X),(X),(X),(X),(X),(X),(X),5.6%,(X),(X),(X),(X),(X),(X),(X),6.0%,(X),(X),(X),(X),(X),(X),(X),6.2%,(X),(X),(X),(X),(X),(X),(X),6.3%,(X),(X),(X),(X),(X),(X),(X),6.6%,(X),(X),(X),(X),(X),(X),(X),5.5%,(X),(X),(X),(X),(X),(X),(X),6.4%,(X),(X),(X),(X),(X),(X),(X),6.9%,(X),(X),(X),(X),(X),(X),(X)
Place of birth,9.4%,(X),(X),(X),(X),(X),(X),(X),10.6%,(X),(X),(X),(X),(X),(X),(X),11.9%,(X),(X),(X),(X),(X),(X),(X),9.3%,(X),(X),(X),(X),(X),(X),(X),9.1%,(X),(X),(X),(X),(X),(X),(X),8.3%,(X),(X),(X),(X),(X),(X),(X),9.2%,(X),(X),(X),(X),(X),(X),(X),8.4%,(X),(X),(X),(X),(X),(X),(X),9.1%,(X),(X),(X),(X),(X),(X),(X),8.3%,(X),(X),(X),(X),(X),(X),(X),8.4%,(X),(X),(X),(X),(X),(X),(X),9.5%,(X),(X),(X),(X),(X),(X),(X),12.4%,(X),(X),(X),(X),(X),(X),(X),8.6%,(X),(X),(X),(X),(X),(X),(X),8.8%,(X),(X),(X),(X),(X),(X),(X),9.1%,(X),(X),(X),(X),(X),(X),(X),6.7%,(X),(X),(X),(X),(X),(X),(X),8.1%,(X),(X),(X),(X),(X),(X),(X),8.2%,(X),(X),(X),(X),(X),(X),(X),8.0%,(X),(X),(X),(X),(X),(X),(X),8.8%,(X),(X),(X),(X),(X),(X),(X)

In [275]:
# Skip the unnamend columns (goes by 8s)

ACS_mod = ACS_mod[ACS_mod.columns[::8]]
ACS_mod

,"Los Angeles County, California","Agoura Hills-Malibu CCD, Los Angeles County, California","Compton CCD, Los Angeles County, California","Downey-Norwalk CCD, Los Angeles County, California","East San Gabriel Valley CCD, Los Angeles County, California","Inglewood CCD, Los Angeles County, California","Long Beach-Lakewood CCD, Los Angeles County, California","Los Angeles CCD, Los Angeles County, California","Newhall CCD, Los Angeles County, California","North Antelope Valley CCD, Los Angeles County, California","Palos Verdes CCD, Los Angeles County, California","Pasadena CCD, Los Angeles County, California","San Fernando Valley CCD, Los Angeles County, California","Santa Monica CCD, Los Angeles County, California","South Antelope Valley CCD, Los Angeles County, California","South Bay Cities CCD, Los Angeles County, California","South Gate-East Los Angeles CCD, Los Angeles County, California","Southwest San Gabriel Valley CCD, Los Angeles County, California","Torrance CCD, Los Angeles County, California","Upper San Gabriel Valley CCD, Los Angeles County, California","Whittier CCD, Los Angeles County, California"
key,,,,,,,,,,,,,,,,,,,,,
NaN,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total
Label,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate
Total population,"10,098,052","64,932","351,459","419,001","958,160","374,562","577,138","2,598,846","261,333","192,039","92,404","274,554","1,860,414","92,078","215,283","139,773","497,962","323,808","146,392","332,369","325,545"
AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Under 5 years,6.2%,3.4%,7.1%,6.3%,6.1%,7.2%,6.7%,6.0%,6.5%,7.6%,4.2%,6.0%,5.8%,4.7%,7.6%,6.3%,7.5%,5.6%,6.1%,5.6%,6.0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100 to 149 percent of the poverty level,10.7%,3.1%,13.2%,10.2%,9.5%,13.0%,10.1%,11.9%,5.1%,10.7%,3.0%,6.7%,10.0%,5.9%,12.3%,2.8%,16.8%,13.8%,4.9%,11.1%,8.8%
At or above 150 percent of the poverty level,73.3%,90.6%,68.8%,77.9%,78.7%,69.3%,73.5%,66.9%,86.8%,66.0%,90.4%,81.6%,75.7%,83.7%,71.4%,92.5%,59.8%,72.5%,88.1%,74.6%,81.4%
PERCENT ALLOCATED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Citizenship status,7.5%,6.7%,10.5%,7.9%,7.5%,6.7%,7.4%,6.5%,6.8%,5.2%,5.3%,6.1%,10.6%,5.6%,6.0%,6.2%,6.3%,6.6%,5.5%,6.4%,6.9%
Place of birth,9.4%,10.6%,11.9%,9.3%,9.1%,8.3%,9.2%,8.4%,9.1%,8.3%,8.4%,9.5%,12.4%,8.6%,8.8%,9.1%,6.7%,8.1%,8.2%,8.0%,8.8%

In [62]:
# names = pd.DataFrame(ACS.iloc[:,0])
# names

                                      Unnamed: 0
0                                            NaN
1                                          Label
2                               Total population
3                                            AGE
4                                  Under 5 years
..                                           ...
59       100 to 149 percent of the poverty level
60  At or above 150 percent of the poverty level
61                             PERCENT ALLOCATED
62                            Citizenship status
63                                Place of birth

[64 rows x 1 columns]

In [230]:
# Look at the unique set of names to compare

ACS_mod.columns

Index(['Los Angeles County, California',
       'Agoura Hills-Malibu CCD, Los Angeles County, California',
       'Compton CCD, Los Angeles County, California',
       'Downey-Norwalk CCD, Los Angeles County, California',
       'East San Gabriel Valley CCD, Los Angeles County, California',
       'Inglewood CCD, Los Angeles County, California',
       'Long Beach-Lakewood CCD, Los Angeles County, California',
       'Los Angeles CCD, Los Angeles County, California',
       'Newhall CCD, Los Angeles County, California',
       'North Antelope Valley CCD, Los Angeles County, California',
       'Palos Verdes CCD, Los Angeles County, California',
       'Pasadena CCD, Los Angeles County, California',
       'San Fernando Valley CCD, Los Angeles County, California',
       'Santa Monica CCD, Los Angeles County, California',
       'South Antelope Valley CCD, Los Angeles County, California',
       'South Bay Cities CCD, Los Angeles County, California',
       'South Gate-East Los Angeles CCD, Los Angeles County, California',
       'Southwest San Gabriel Valley CCD, Los Angeles County, California',
       'Torrance CCD, Los Angeles County, California',
       'Upper San Gabriel Valley CCD, Los Angeles County, California',
       'Whittier CCD, Los Angeles County, California',
       'Los Angeles-Long Beach-Anaheim, CA Metro Area'],
      dtype='object')

In [277]:
# Rewrite the set of names to match with pedestrian crash data

ACS_mod = ACS_mod.set_axis(['Los Angeles County, California',
       'Agoura Hills-Malibu',
       'Compton',
       'Downey-Norwalk',
       'East San Gabriel',
       'Inglewood',
       'Long Beach-Lakewood',
       'Los Angeles',
       'Newhall',
       'North Antelope',
       'Palos Verdes',
       'Pasadena',
       'San Fernando',
       'Santa Monica',
       'South Antelope',
       'South Bay Cities',
       'South Gate-East Los Angeles',
       'Southwest San Gabriel',
       'Torrance',
       'Upper San Gabriel',
       'Whittier',
       # 'Los Angeles-Long Beach-Anaheim, CA Metro Area' #Need to add except in 2018
                           ], axis=1)
ACS_mod

,"Los Angeles County, California",Agoura Hills-Malibu,Compton,Downey-Norwalk,East San Gabriel,Inglewood,Long Beach-Lakewood,Los Angeles,Newhall,North Antelope,Palos Verdes,Pasadena,San Fernando,Santa Monica,South Antelope,South Bay Cities,South Gate-East Los Angeles,Southwest San Gabriel,Torrance,Upper San Gabriel,Whittier
key,,,,,,,,,,,,,,,,,,,,,
NaN,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total,Total
Label,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate,Estimate
Total population,"10,098,052","64,932","351,459","419,001","958,160","374,562","577,138","2,598,846","261,333","192,039","92,404","274,554","1,860,414","92,078","215,283","139,773","497,962","323,808","146,392","332,369","325,545"
AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Under 5 years,6.2%,3.4%,7.1%,6.3%,6.1%,7.2%,6.7%,6.0%,6.5%,7.6%,4.2%,6.0%,5.8%,4.7%,7.6%,6.3%,7.5%,5.6%,6.1%,5.6%,6.0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100 to 149 percent of the poverty level,10.7%,3.1%,13.2%,10.2%,9.5%,13.0%,10.1%,11.9%,5.1%,10.7%,3.0%,6.7%,10.0%,5.9%,12.3%,2.8%,16.8%,13.8%,4.9%,11.1%,8.8%
At or above 150 percent of the poverty level,73.3%,90.6%,68.8%,77.9%,78.7%,69.3%,73.5%,66.9%,86.8%,66.0%,90.4%,81.6%,75.7%,83.7%,71.4%,92.5%,59.8%,72.5%,88.1%,74.6%,81.4%
PERCENT ALLOCATED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Citizenship status,7.5%,6.7%,10.5%,7.9%,7.5%,6.7%,7.4%,6.5%,6.8%,5.2%,5.3%,6.1%,10.6%,5.6%,6.0%,6.2%,6.3%,6.6%,5.5%,6.4%,6.9%
Place of birth,9.4%,10.6%,11.9%,9.3%,9.1%,8.3%,9.2%,8.4%,9.1%,8.3%,8.4%,9.5%,12.4%,8.6%,8.8%,9.1%,6.7%,8.1%,8.2%,8.0%,8.8%

In [278]:
# Select row

ACS_mod.loc[["Total population"]]

,"Los Angeles County, California",Agoura Hills-Malibu,Compton,Downey-Norwalk,East San Gabriel,Inglewood,Long Beach-Lakewood,Los Angeles,Newhall,North Antelope,Palos Verdes,Pasadena,San Fernando,Santa Monica,South Antelope,South Bay Cities,South Gate-East Los Angeles,Southwest San Gabriel,Torrance,Upper San Gabriel,Whittier
key,,,,,,,,,,,,,,,,,,,,,
Total population,"10,098,052","64,932","351,459","419,001","958,160","374,562","577,138","2,598,846","261,333","192,039","92,404","274,554","1,860,414","92,078","215,283","139,773","497,962","323,808","146,392","332,369","325,545"

In [279]:
# Select key rows for investigation

ACS_mod = ACS_mod.loc[["Total population", "Median age (years)", "High school graduate (includes equivalency)",
        "Less than high school graduate",
        "Population 15 years and over",
        "Median income (dollars)",
        "Population for whom poverty status is determined",
        "Below 100 percent of the poverty level"]]
ACS_mod

,"Los Angeles County, California",Agoura Hills-Malibu,Compton,Downey-Norwalk,East San Gabriel,Inglewood,Long Beach-Lakewood,Los Angeles,Newhall,North Antelope,Palos Verdes,Pasadena,San Fernando,Santa Monica,South Antelope,South Bay Cities,South Gate-East Los Angeles,Southwest San Gabriel,Torrance,Upper San Gabriel,Whittier
key,,,,,,,,,,,,,,,,,,,,,
Total population,"10,098,052","64,932","351,459","419,001","958,160","374,562","577,138","2,598,846","261,333","192,039","92,404","274,554","1,860,414","92,078","215,283","139,773","497,962","323,808","146,392","332,369","325,545"
Median age (years),36.2,45.1,33.1,35.8,36.9,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,40.9,41.7,39.5,36.9
High school graduate (includes equivalency),20.7%,11.7%,25.8%,24.7%,23.8%,24.1%,18.9%,18.0%,18.2%,30.2%,12.7%,13.2%,20.7%,8.3%,25.0%,9.3%,24.3%,25.3%,16.0%,22.1%,28.6%
Less than high school graduate,21.3%,2.6%,32.7%,22.8%,19.6%,24.7%,18.7%,23.8%,9.8%,17.7%,4.9%,9.5%,18.2%,5.2%,24.0%,3.1%,49.8%,23.7%,5.8%,23.8%,18.6%
Population 15 years and over,"8,238,808","55,178","276,034","335,208","782,727","296,679","467,862","2,155,061","206,153","147,769","77,071","228,556","1,538,569","80,689","164,950","113,921","380,768","273,833","121,128","271,261","265,391"
Population 15 years and over,"8,238,808","55,178","276,034","335,208","782,727","296,679","467,862","2,155,061","206,153","147,769","77,071","228,556","1,538,569","80,689","164,950","113,921","380,768","273,833","121,128","271,261","265,391"
Median income (dollars),"27,856","51,970","23,818","27,706","26,877","25,119","30,587","26,472","39,705","30,626","50,473","40,672","29,234","54,022","27,095","63,844","20,407","23,867","42,808","26,206","30,132"
Population for whom poverty status is determined,"9,947,799","61,945","346,675","415,237","937,341","372,299","570,151","2,543,269","253,705","184,377","91,807","271,572","1,843,478","91,213","213,877","139,451","495,905","320,850","145,494","329,321","319,832"
Below 100 percent of the poverty level,16.0%,6.3%,18.0%,12.0%,11.8%,17.7%,16.5%,21.2%,8.2%,23.3%,6.5%,11.6%,14.3%,10.4%,16.2%,4.7%,23.4%,13.7%,7.0%,14.3%,9.9%

In [280]:
# Change columns to lowercase

ACS_mod.columns = map(str.lower, ACS_mod.columns)
ACS_mod

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,east san gabriel,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,southwest san gabriel,torrance,upper san gabriel,whittier
key,,,,,,,,,,,,,,,,,,,,,
Total population,"10,098,052","64,932","351,459","419,001","958,160","374,562","577,138","2,598,846","261,333","192,039","92,404","274,554","1,860,414","92,078","215,283","139,773","497,962","323,808","146,392","332,369","325,545"
Median age (years),36.2,45.1,33.1,35.8,36.9,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,40.9,41.7,39.5,36.9
High school graduate (includes equivalency),20.7%,11.7%,25.8%,24.7%,23.8%,24.1%,18.9%,18.0%,18.2%,30.2%,12.7%,13.2%,20.7%,8.3%,25.0%,9.3%,24.3%,25.3%,16.0%,22.1%,28.6%
Less than high school graduate,21.3%,2.6%,32.7%,22.8%,19.6%,24.7%,18.7%,23.8%,9.8%,17.7%,4.9%,9.5%,18.2%,5.2%,24.0%,3.1%,49.8%,23.7%,5.8%,23.8%,18.6%
Population 15 years and over,"8,238,808","55,178","276,034","335,208","782,727","296,679","467,862","2,155,061","206,153","147,769","77,071","228,556","1,538,569","80,689","164,950","113,921","380,768","273,833","121,128","271,261","265,391"
Population 15 years and over,"8,238,808","55,178","276,034","335,208","782,727","296,679","467,862","2,155,061","206,153","147,769","77,071","228,556","1,538,569","80,689","164,950","113,921","380,768","273,833","121,128","271,261","265,391"
Median income (dollars),"27,856","51,970","23,818","27,706","26,877","25,119","30,587","26,472","39,705","30,626","50,473","40,672","29,234","54,022","27,095","63,844","20,407","23,867","42,808","26,206","30,132"
Population for whom poverty status is determined,"9,947,799","61,945","346,675","415,237","937,341","372,299","570,151","2,543,269","253,705","184,377","91,807","271,572","1,843,478","91,213","213,877","139,451","495,905","320,850","145,494","329,321","319,832"
Below 100 percent of the poverty level,16.0%,6.3%,18.0%,12.0%,11.8%,17.7%,16.5%,21.2%,8.2%,23.3%,6.5%,11.6%,14.3%,10.4%,16.2%,4.7%,23.4%,13.7%,7.0%,14.3%,9.9%

In [281]:
# Concatenate like cities with pedestrian deaths
pd.set_option('display.max_columns', None)
crash_data19 = pd.concat([ACS_mod, crash19], ignore_index=False, sort=False)
crash_data19

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,east san gabriel,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,southwest san gabriel,torrance,upper san gabriel,whittier,unincorporated,long beach,pomona,glendale,alhambra,west hollywood,lancaster,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre
Total population,"10,098,052","64,932","351,459","419,001","958,160","374,562","577,138","2,598,846","261,333","192,039","92,404","274,554","1,860,414","92,078","215,283","139,773","497,962","323,808","146,392","332,369","325,545",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median age (years),36.2,45.1,33.1,35.8,36.9,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,40.9,41.7,39.5,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
High school graduate (includes equivalency),20.7%,11.7%,25.8%,24.7%,23.8%,24.1%,18.9%,18.0%,18.2%,30.2%,12.7%,13.2%,20.7%,8.3%,25.0%,9.3%,24.3%,25.3%,16.0%,22.1%,28.6%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Less than high school graduate,21.3%,2.6%,32.7%,22.8%,19.6%,24.7%,18.7%,23.8%,9.8%,17.7%,4.9%,9.5%,18.2%,5.2%,24.0%,3.1%,49.8%,23.7%,5.8%,23.8%,18.6%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population 15 years and over,"8,238,808","55,178","276,034","335,208","782,727","296,679","467,862","2,155,061","206,153","147,769","77,071","228,556","1,538,569","80,689","164,950","113,921","380,768","273,833","121,128","271,261","265,391",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population 15 years and over,"8,238,808","55,178","276,034","335,208","782,727","296,679","467,862","2,155,061","206,153","147,769","77,071","228,556","1,538,569","80,689","164,950","113,921","380,768","273,833","121,128","271,261","265,391",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median income (dollars),"27,856","51,970","23,818","27,706","26,877","25,119","30,587","26,472","39,705","30,626","50,473","40,672","29,234","54,022","27,095","63,844","20,407","23,867","42,808","26,206","30,132",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population for whom poverty status is determined,"9,947,799","61,945","346,675","415,237","937,341","372,299","570,151","2,543,269","253,705","184,377","91,807","271,572","1,843,478","91,213","213,877","139,451","495,905","320,850","145,494","329,321","319,832",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Below 100 percent of the poverty level,16.0%,6.3%,18.0%,12.0%,11.8%,17.7%,16.5%,21.2%,8.2%,23.3%,6.5%,11.6%,14.3%,10.4%,16.2%,4.7%,23.4%,13.7%,7.0%,14.3%,9.9%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,NaN,43,NaN,NaN,58,NaN,3215,NaN,NaN,NaN,75,6,84,NaN,NaN,NaN,NaN,47,NaN,30,394.0,331.0,84.0,78.0,57.0,56.0,51.0,43.0,42.0,42.0,37.0,35.0,35.0,33.0,32.0,31.0,31.0,31.0,30.0,29.0,27.0,27.0,26.0,26.0,25.0,25.0,24.0,24.0,21.0,20.0,19.0,19.0,18.0,15.0,14.0,13.0,12.0,12.0,12.0,12.0,11.0,11.0,10.0,10.0,10.0,9.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0

In [236]:
# Look the cities
crash_data19.columns

Index(['los angeles county, california', 'agoura hills-malibu', 'compton',
       'downey-norwalk', 'east san gabriel', 'inglewood',
       'long beach-lakewood', 'los angeles', 'newhall', 'north antelope',
       'palos verdes', 'pasadena', 'san fernando', 'santa monica',
       'south antelope', 'south bay cities', 'south gate-east los angeles',
       'southwest san gabriel', 'torrance', 'upper san gabriel', 'whittier',
       'los angeles-long beach-anaheim, ca metro area', 'unincorporated',
       'long beach', 'glendale', 'pomona', 'west hollywood', 'norwalk',
       'gardena', 'lancaster', 'south gate', 'downey', 'alhambra',
       'montebello', 'palmdale', 'hawthorne', 'el monte', 'beverly hills',
       'monterey park', 'huntington park', 'lynwood', 'culver city',
       'bellflower', 'west covina', 'carson', 'lakewood', 'redondo beach',
       'santa clarita', 'paramount', 'rosemead', 'pico rivera', 'covina',
       'baldwin park', 'bell', 'bell gardens', 'azusa', 'diamond bar',
       'arcadia', 'la puente', 'san gabriel', 'manhattan beach',
       'south el monte', 'malibu', 'industry', 'cerritos', 'glendora',
       'el segundo', 'claremont', 'lawndale', 'temple city', 'commerce',
       'maywood', 'la mirada', 'cudahy', 'south pasadena', 'santa fe springs',
       'duarte', 'hawaiian gardens', 'monrovia', 'signal hill',
       'hermosa beach', 'calabasas', 'la verne', 'san dimas', 'agoura hills',
       'artesia', 'la canada-flintridge', 'vernon', 'walnut', 'burbank',
       'sierra madre', 'san marino', 'palos verdes est', 'westlake village',
       'irwindale'],
      dtype='object')

In [282]:
# Count the length
len(crash_data19.columns)

94

In [283]:
# Transpose to count the number of values

c_vis = crash_data19.loc[["count"]].T
c_vis

                               count
los angeles county, california   NaN
agoura hills-malibu              NaN
compton                           43
downey-norwalk                   NaN
east san gabriel                 NaN
...                              ...
walnut                           2.0
hidden hills                     2.0
burbank                          2.0
palos verdes est                 1.0
sierra madre                     1.0

[94 rows x 1 columns]

In [284]:
# Count non-NAs
c_vis.nunique()

count    43
dtype: int64

In [285]:
# Create Raw DataFrame
crash_data19_r = crash_data19.dropna(axis='columns')
crash_data19_r

,compton,inglewood,los angeles,pasadena,san fernando,santa monica,torrance,whittier
Total population,"351,459","374,562","2,598,846","274,554","1,860,414","92,078","146,392","325,545"
Median age (years),33.1,35.0,34.9,40.7,37.7,39.9,41.7,36.9
High school graduate (includes equivalency),25.8%,24.1%,18.0%,13.2%,20.7%,8.3%,16.0%,28.6%
Less than high school graduate,32.7%,24.7%,23.8%,9.5%,18.2%,5.2%,5.8%,18.6%
Population 15 years and over,"276,034","296,679","2,155,061","228,556","1,538,569","80,689","121,128","265,391"
Population 15 years and over,"276,034","296,679","2,155,061","228,556","1,538,569","80,689","121,128","265,391"
Median income (dollars),"23,818","25,119","26,472","40,672","29,234","54,022","42,808","30,132"
Population for whom poverty status is determined,"346,675","372,299","2,543,269","271,572","1,843,478","91,213","145,494","319,832"
Below 100 percent of the poverty level,18.0%,17.7%,21.2%,11.6%,14.3%,10.4%,7.0%,9.9%
count,43,58,3215,75,6,84,47,30

In [286]:
# Create checkpoint for transformed data
crash_data19_t = crash_data19
crash_data19_t

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,east san gabriel,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,southwest san gabriel,torrance,upper san gabriel,whittier,unincorporated,long beach,pomona,glendale,alhambra,west hollywood,lancaster,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre
Total population,"10,098,052","64,932","351,459","419,001","958,160","374,562","577,138","2,598,846","261,333","192,039","92,404","274,554","1,860,414","92,078","215,283","139,773","497,962","323,808","146,392","332,369","325,545",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median age (years),36.2,45.1,33.1,35.8,36.9,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,40.9,41.7,39.5,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
High school graduate (includes equivalency),20.7%,11.7%,25.8%,24.7%,23.8%,24.1%,18.9%,18.0%,18.2%,30.2%,12.7%,13.2%,20.7%,8.3%,25.0%,9.3%,24.3%,25.3%,16.0%,22.1%,28.6%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Less than high school graduate,21.3%,2.6%,32.7%,22.8%,19.6%,24.7%,18.7%,23.8%,9.8%,17.7%,4.9%,9.5%,18.2%,5.2%,24.0%,3.1%,49.8%,23.7%,5.8%,23.8%,18.6%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population 15 years and over,"8,238,808","55,178","276,034","335,208","782,727","296,679","467,862","2,155,061","206,153","147,769","77,071","228,556","1,538,569","80,689","164,950","113,921","380,768","273,833","121,128","271,261","265,391",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population 15 years and over,"8,238,808","55,178","276,034","335,208","782,727","296,679","467,862","2,155,061","206,153","147,769","77,071","228,556","1,538,569","80,689","164,950","113,921","380,768","273,833","121,128","271,261","265,391",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median income (dollars),"27,856","51,970","23,818","27,706","26,877","25,119","30,587","26,472","39,705","30,626","50,473","40,672","29,234","54,022","27,095","63,844","20,407","23,867","42,808","26,206","30,132",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population for whom poverty status is determined,"9,947,799","61,945","346,675","415,237","937,341","372,299","570,151","2,543,269","253,705","184,377","91,807","271,572","1,843,478","91,213","213,877","139,451","495,905","320,850","145,494","329,321","319,832",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Below 100 percent of the poverty level,16.0%,6.3%,18.0%,12.0%,11.8%,17.7%,16.5%,21.2%,8.2%,23.3%,6.5%,11.6%,14.3%,10.4%,16.2%,4.7%,23.4%,13.7%,7.0%,14.3%,9.9%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,NaN,43,NaN,NaN,58,NaN,3215,NaN,NaN,NaN,75,6,84,NaN,NaN,NaN,NaN,47,NaN,30,394.0,331.0,84.0,78.0,57.0,56.0,51.0,43.0,42.0,42.0,37.0,35.0,35.0,33.0,32.0,31.0,31.0,31.0,30.0,29.0,27.0,27.0,26.0,26.0,25.0,25.0,24.0,24.0,21.0,20.0,19.0,19.0,18.0,15.0,14.0,13.0,12.0,12.0,12.0,12.0,11.0,11.0,10.0,10.0,10.0,9.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0

In [287]:
# # Combine into CCD designations -- agoura hills-malibu
crash_data19_t['agoura hills-malibu'].loc[['count']] = (
    crash_data19_t['agoura hills'].loc[['count']] + crash_data19_t['malibu'].loc[['count']]
                    )


crash_data19_t['agoura hills-malibu'].loc[['count']]

C:\Users\willi\AppData\Local\Temp\ipykernel_19200\3971100415.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crash_data19_t['agoura hills-malibu'].loc[['count']] = (

count    16.0
Name: agoura hills-malibu, dtype: object

In [288]:
# # Combine into CCD designations -- downey-norwalk
crash_data19_t['downey-norwalk'].loc[['count']] = (
    crash_data19_t['downey'].loc[['count']] + crash_data19_t['norwalk'].loc[['count']])


crash_data19_t['downey-norwalk'].loc[['count']]

C:\Users\willi\AppData\Local\Temp\ipykernel_19200\3772993649.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crash_data19_t['downey-norwalk'].loc[['count']] = (

count    74.0
Name: downey-norwalk, dtype: object

In [289]:
# # Combine into CCD designations -- san fernando
crash_data19_t['san fernando'].loc[['count']] = (
    crash_data19_t['san fernando'].loc[['count']] + crash_data19_t['glendale'].loc[['count']]
    +  crash_data19_t['burbank'].loc[['count']] + crash_data19_t['calabasas'].loc[['count']])


crash_data19_t['san fernando'].loc[['count']]

C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2502470272.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crash_data19_t['san fernando'].loc[['count']] = (

count    90.0
Name: san fernando, dtype: object

In [290]:
# # Combine into CCD designations -- long beach-lakewood
crash_data19_t['long beach-lakewood'].loc[['count']] = (
    crash_data19_t['long beach'].loc[['count']] + crash_data19_t['lakewood'].loc[['count']])


crash_data19_t['long beach-lakewood'].loc[['count']]

C:\Users\willi\AppData\Local\Temp\ipykernel_19200\4148259818.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crash_data19_t['long beach-lakewood'].loc[['count']] = (

count    362.0
Name: long beach-lakewood, dtype: object

In [306]:
# # Combine into CCD designations -- palos verdes
crash_data19_t['palos verdes'].loc[['count']] = (
    # crash_data19_t['rancho palos verdes'].loc[['count']] # Doesn't exist in 2012, 2015, 2016, 2017
     crash_data19_t['palos verdes est'].loc[['count']]) # Doesn't exist in 2014 or 2016

crash_data19_t['palos verdes'].loc[['count']]

index
count    1.0
Name: palos verdes, dtype: float64

In [292]:
# # Combine into CCD designations -- newhall
crash_data19_t['newhall'].loc[['count']] = crash_data19_t['santa clarita'].loc[['count']] 

crash_data19_t['newhall'].loc[['count']]

C:\Users\willi\AppData\Local\Temp\ipykernel_19200\893345965.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crash_data19_t['newhall'].loc[['count']] = crash_data19_t['santa clarita'].loc[['count']]

count    25.0
Name: newhall, dtype: object

In [293]:
# # Combine into CCD designations -- south bay cities
crash_data19_t['south bay cities'].loc[['count']] = (
    crash_data19_t['carson'].loc[['count']] 
    + crash_data19_t['el segundo'].loc[['count']] + crash_data19_t['gardena'].loc[['count']]
    +  crash_data19_t['hawthorne'].loc[['count']]  + crash_data19_t['hermosa beach'].loc[['count']]   
    + crash_data19_t['lawndale'].loc[['count']] + crash_data19_t['manhattan beach'].loc[['count']] 
    + crash_data19_t['redondo beach'].loc[['count']])


crash_data19_t['south bay cities'].loc[['count']]

C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2224110969.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crash_data19_t['south bay cities'].loc[['count']] = (

count    147.0
Name: south bay cities, dtype: object

In [294]:
# # Combine into CCD designations -- south gate-east la
crash_data19_t['south gate-east los angeles'].loc[['count']] = (
    crash_data19_t['south gate'].loc[['count']] + crash_data19_t['commerce'].loc[['count']])


crash_data19_t['south gate-east los angeles'].loc[['count']]

C:\Users\willi\AppData\Local\Temp\ipykernel_19200\3582171466.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crash_data19_t['south gate-east los angeles'].loc[['count']] = (

count    41.0
Name: south gate-east los angeles, dtype: object

In [295]:
# Drop duplicate index
crash_data19_t = crash_data19_t.reset_index().drop_duplicates(subset = 'index', keep= 'last').set_index('index')
crash_data19_t

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,east san gabriel,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,southwest san gabriel,torrance,upper san gabriel,whittier,unincorporated,long beach,pomona,glendale,alhambra,west hollywood,lancaster,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Total population,"10,098,052","64,932","351,459","419,001","958,160","374,562","577,138","2,598,846","261,333","192,039","92,404","274,554","1,860,414","92,078","215,283","139,773","497,962","323,808","146,392","332,369","325,545",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median age (years),36.2,45.1,33.1,35.8,36.9,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,40.9,41.7,39.5,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
High school graduate (includes equivalency),20.7%,11.7%,25.8%,24.7%,23.8%,24.1%,18.9%,18.0%,18.2%,30.2%,12.7%,13.2%,20.7%,8.3%,25.0%,9.3%,24.3%,25.3%,16.0%,22.1%,28.6%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Less than high school graduate,21.3%,2.6%,32.7%,22.8%,19.6%,24.7%,18.7%,23.8%,9.8%,17.7%,4.9%,9.5%,18.2%,5.2%,24.0%,3.1%,49.8%,23.7%,5.8%,23.8%,18.6%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population 15 years and over,"8,238,808","55,178","276,034","335,208","782,727","296,679","467,862","2,155,061","206,153","147,769","77,071","228,556","1,538,569","80,689","164,950","113,921","380,768","273,833","121,128","271,261","265,391",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median income (dollars),"27,856","51,970","23,818","27,706","26,877","25,119","30,587","26,472","39,705","30,626","50,473","40,672","29,234","54,022","27,095","63,844","20,407","23,867","42,808","26,206","30,132",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Population for whom poverty status is determined,"9,947,799","61,945","346,675","415,237","937,341","372,299","570,151","2,543,269","253,705","184,377","91,807","271,572","1,843,478","91,213","213,877","139,451","495,905","320,850","145,494","329,321","319,832",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Below 100 percent of the poverty level,16.0%,6.3%,18.0%,12.0%,11.8%,17.7%,16.5%,21.2%,8.2%,23.3%,6.5%,11.6%,14.3%,10.4%,16.2%,4.7%,23.4%,13.7%,7.0%,14.3%,9.9%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,16.0,43,74.0,NaN,58,362.0,3215,25.0,NaN,1.0,75,90.0,84,NaN,147.0,41.0,NaN,47,NaN,30,394.0,331.0,84.0,78.0,57.0,56.0,51.0,43.0,42.0,42.0,37.0,35.0,35.0,33.0,32.0,31.0,31.0,31.0,30.0,29.0,27.0,27.0,26.0,26.0,25.0,25.0,24.0,24.0,21.0,20.0,19.0,19.0,18.0,15.0,14.0,13.0,12.0,12.0,12.0,12.0,11.0,11.0,10.0,10.0,10.0,9.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0

In [94]:
crash_data19_t.index

Index(['Total population', 'Median age (years)',
       'High school graduate (includes equivalency)',
       'Less than high school graduate', 'Population 15 years and over',
       'Median income (dollars)',
       'Population for whom poverty status is determined',
       'Below 100 percent of the poverty level', 'count'],
      dtype='object', name='index')

In [296]:
# Set new simplified index
# crash_data19_t = crash_data19_t.set_index()

crash_data19_t.rename(index={'Total population': 't_pop', 'Median age (years)': 'med_age',
       'High school graduate (includes equivalency)': 'hs_g',
       'Less than high school graduate': "lhs_g", 'Population 15 years and over': 'pop_15',
       'Median income (dollars)': 'med_inc',
       'Population for whom poverty status is determined': 'pop_det_pov',
       'Below 100 percent of the poverty level': 'pov_level'},inplace=True)
crash_data19_t

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,east san gabriel,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,southwest san gabriel,torrance,upper san gabriel,whittier,unincorporated,long beach,pomona,glendale,alhambra,west hollywood,lancaster,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
t_pop,"10,098,052","64,932","351,459","419,001","958,160","374,562","577,138","2,598,846","261,333","192,039","92,404","274,554","1,860,414","92,078","215,283","139,773","497,962","323,808","146,392","332,369","325,545",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_age,36.2,45.1,33.1,35.8,36.9,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,40.9,41.7,39.5,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hs_g,20.7%,11.7%,25.8%,24.7%,23.8%,24.1%,18.9%,18.0%,18.2%,30.2%,12.7%,13.2%,20.7%,8.3%,25.0%,9.3%,24.3%,25.3%,16.0%,22.1%,28.6%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lhs_g,21.3%,2.6%,32.7%,22.8%,19.6%,24.7%,18.7%,23.8%,9.8%,17.7%,4.9%,9.5%,18.2%,5.2%,24.0%,3.1%,49.8%,23.7%,5.8%,23.8%,18.6%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_15,"8,238,808","55,178","276,034","335,208","782,727","296,679","467,862","2,155,061","206,153","147,769","77,071","228,556","1,538,569","80,689","164,950","113,921","380,768","273,833","121,128","271,261","265,391",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_inc,"27,856","51,970","23,818","27,706","26,877","25,119","30,587","26,472","39,705","30,626","50,473","40,672","29,234","54,022","27,095","63,844","20,407","23,867","42,808","26,206","30,132",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_det_pov,"9,947,799","61,945","346,675","415,237","937,341","372,299","570,151","2,543,269","253,705","184,377","91,807","271,572","1,843,478","91,213","213,877","139,451","495,905","320,850","145,494","329,321","319,832",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pov_level,16.0%,6.3%,18.0%,12.0%,11.8%,17.7%,16.5%,21.2%,8.2%,23.3%,6.5%,11.6%,14.3%,10.4%,16.2%,4.7%,23.4%,13.7%,7.0%,14.3%,9.9%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,16.0,43,74.0,NaN,58,362.0,3215,25.0,NaN,1.0,75,90.0,84,NaN,147.0,41.0,NaN,47,NaN,30,394.0,331.0,84.0,78.0,57.0,56.0,51.0,43.0,42.0,42.0,37.0,35.0,35.0,33.0,32.0,31.0,31.0,31.0,30.0,29.0,27.0,27.0,26.0,26.0,25.0,25.0,24.0,24.0,21.0,20.0,19.0,19.0,18.0,15.0,14.0,13.0,12.0,12.0,12.0,12.0,11.0,11.0,10.0,10.0,10.0,9.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0

In [297]:
# Remove commas
crash_data19_t.replace(',','', regex=True, inplace = True)
crash_data19_t

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,east san gabriel,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,southwest san gabriel,torrance,upper san gabriel,whittier,unincorporated,long beach,pomona,glendale,alhambra,west hollywood,lancaster,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
t_pop,10098052,64932,351459,419001,958160,374562,577138,2598846,261333,192039,92404,274554,1860414,92078,215283,139773,497962,323808,146392,332369,325545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_age,36.2,45.1,33.1,35.8,36.9,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,40.9,41.7,39.5,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hs_g,20.7%,11.7%,25.8%,24.7%,23.8%,24.1%,18.9%,18.0%,18.2%,30.2%,12.7%,13.2%,20.7%,8.3%,25.0%,9.3%,24.3%,25.3%,16.0%,22.1%,28.6%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lhs_g,21.3%,2.6%,32.7%,22.8%,19.6%,24.7%,18.7%,23.8%,9.8%,17.7%,4.9%,9.5%,18.2%,5.2%,24.0%,3.1%,49.8%,23.7%,5.8%,23.8%,18.6%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_15,8238808,55178,276034,335208,782727,296679,467862,2155061,206153,147769,77071,228556,1538569,80689,164950,113921,380768,273833,121128,271261,265391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_inc,27856,51970,23818,27706,26877,25119,30587,26472,39705,30626,50473,40672,29234,54022,27095,63844,20407,23867,42808,26206,30132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_det_pov,9947799,61945,346675,415237,937341,372299,570151,2543269,253705,184377,91807,271572,1843478,91213,213877,139451,495905,320850,145494,329321,319832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pov_level,16.0%,6.3%,18.0%,12.0%,11.8%,17.7%,16.5%,21.2%,8.2%,23.3%,6.5%,11.6%,14.3%,10.4%,16.2%,4.7%,23.4%,13.7%,7.0%,14.3%,9.9%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,16.0,43,74.0,NaN,58,362.0,3215,25.0,NaN,1.0,75,90.0,84,NaN,147.0,41.0,NaN,47,NaN,30,394.0,331.0,84.0,78.0,57.0,56.0,51.0,43.0,42.0,42.0,37.0,35.0,35.0,33.0,32.0,31.0,31.0,31.0,30.0,29.0,27.0,27.0,26.0,26.0,25.0,25.0,24.0,24.0,21.0,20.0,19.0,19.0,18.0,15.0,14.0,13.0,12.0,12.0,12.0,12.0,11.0,11.0,10.0,10.0,10.0,9.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0

In [298]:
# Convert to numeric percentage
crash_data19_t.replace('%','', regex=True, inplace = True)
crash_data19_t

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,east san gabriel,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,southwest san gabriel,torrance,upper san gabriel,whittier,unincorporated,long beach,pomona,glendale,alhambra,west hollywood,lancaster,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
t_pop,10098052,64932,351459,419001,958160,374562,577138,2598846,261333,192039,92404,274554,1860414,92078,215283,139773,497962,323808,146392,332369,325545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_age,36.2,45.1,33.1,35.8,36.9,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,40.9,41.7,39.5,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hs_g,20.7,11.7,25.8,24.7,23.8,24.1,18.9,18.0,18.2,30.2,12.7,13.2,20.7,8.3,25.0,9.3,24.3,25.3,16.0,22.1,28.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lhs_g,21.3,2.6,32.7,22.8,19.6,24.7,18.7,23.8,9.8,17.7,4.9,9.5,18.2,5.2,24.0,3.1,49.8,23.7,5.8,23.8,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_15,8238808,55178,276034,335208,782727,296679,467862,2155061,206153,147769,77071,228556,1538569,80689,164950,113921,380768,273833,121128,271261,265391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_inc,27856,51970,23818,27706,26877,25119,30587,26472,39705,30626,50473,40672,29234,54022,27095,63844,20407,23867,42808,26206,30132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_det_pov,9947799,61945,346675,415237,937341,372299,570151,2543269,253705,184377,91807,271572,1843478,91213,213877,139451,495905,320850,145494,329321,319832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pov_level,16.0,6.3,18.0,12.0,11.8,17.7,16.5,21.2,8.2,23.3,6.5,11.6,14.3,10.4,16.2,4.7,23.4,13.7,7.0,14.3,9.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,16.0,43,74.0,NaN,58,362.0,3215,25.0,NaN,1.0,75,90.0,84,NaN,147.0,41.0,NaN,47,NaN,30,394.0,331.0,84.0,78.0,57.0,56.0,51.0,43.0,42.0,42.0,37.0,35.0,35.0,33.0,32.0,31.0,31.0,31.0,30.0,29.0,27.0,27.0,26.0,26.0,25.0,25.0,24.0,24.0,21.0,20.0,19.0,19.0,18.0,15.0,14.0,13.0,12.0,12.0,12.0,12.0,11.0,11.0,10.0,10.0,10.0,9.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0

In [299]:
# Turn DataFrame into numeric
crash_data19_t = crash_data19_t.apply(pd.to_numeric)

# crash_data19_t = crash_data19_t.apply(np.round)

In [300]:
# Combine southwest san gabriel, upper san gabriel, and east san gabriel into san gabriel

# Total Population
crash_data19_t['san gabriel'].loc[['t_pop']] = (
    crash_data19_t['southwest san gabriel'].loc[['t_pop']]
    + crash_data19_t['upper san gabriel'].loc[['t_pop']]
    + crash_data19_t['east san gabriel'].loc[['t_pop']]
        )

# Median Age
crash_data19_t['san gabriel'].loc[['med_age']] = statistics.median([
(int(crash_data19_t['southwest san gabriel'].loc[['med_age']])),
(int(crash_data19_t['upper san gabriel'].loc[['med_age']])),
(int(crash_data19_t['east san gabriel'].loc[['med_age']]))])
     

# Only High school graduation (percent of pop %)includes weights
crash_data19_t['san gabriel'].loc[['hs_g']] = np.round((
((int(crash_data19_t['southwest san gabriel'].loc[['t_pop']])
  /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
    * crash_data19_t['southwest san gabriel'].loc[['hs_g']])  # value
    + ((int(crash_data19_t['upper san gabriel'].loc[['t_pop']])
     /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
    * int(crash_data19_t['upper san gabriel'].loc[['hs_g']]))     # value
    + ((int(crash_data19_t['east san gabriel'].loc[['t_pop']])
     /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
    * int(crash_data19_t['east san gabriel'].loc[['hs_g']]))     # value
        ), decimals =2)

# Less than High school graduation (percent of pop %) includes weights
crash_data19_t['san gabriel'].loc[['lhs_g']] = np.round((
((int(crash_data19_t['southwest san gabriel'].loc[['t_pop']])
  /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
    * crash_data19_t['southwest san gabriel'].loc[['lhs_g']])  # value
    + ((int(crash_data19_t['upper san gabriel'].loc[['t_pop']])
     /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
    * int(crash_data19_t['upper san gabriel'].loc[['lhs_g']]))     # value
    + ((int(crash_data19_t['east san gabriel'].loc[['t_pop']])
     /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
    * int(crash_data19_t['east san gabriel'].loc[['lhs_g']]))     # value
        ), decimals =2)

 
# Population Over 15
crash_data19_t['san gabriel'].loc[['pop_15']] = (
    crash_data19_t['southwest san gabriel'].loc[['pop_15']]
    + crash_data19_t['upper san gabriel'].loc[['pop_15']]
    + crash_data19_t['east san gabriel'].loc[['pop_15']]
        )
 
# Median Income
crash_data19_t['san gabriel'].loc[['med_inc']] = statistics.median([
(int(crash_data19_t['southwest san gabriel'].loc[['med_inc']])),
(int(crash_data19_t['upper san gabriel'].loc[['med_inc']])),
(int(crash_data19_t['east san gabriel'].loc[['med_inc']]))])
 
 
 
# Population Used to Determine Poverty
crash_data19_t['san gabriel'].loc[['pop_det_pov']] = (
    crash_data19_t['southwest san gabriel'].loc[['pop_det_pov']]
    + crash_data19_t['upper san gabriel'].loc[['pop_det_pov']]
    + crash_data19_t['east san gabriel'].loc[['pop_det_pov']]
        )

# Percent of Population under Poverty Line (%) including weights
crash_data19_t['san gabriel'].loc[['pov_level']] = np.round((
((int(crash_data19_t['southwest san gabriel'].loc[['pop_det_pov']])
  /int(crash_data19_t['san gabriel'].loc[['pop_det_pov']]))          #weight
    * crash_data19_t['southwest san gabriel'].loc[['pov_level']])  # value
    + ((int(crash_data19_t['upper san gabriel'].loc[['pop_det_pov']])
     /int(crash_data19_t['san gabriel'].loc[['pop_det_pov']]))          #weight
    * int(crash_data19_t['upper san gabriel'].loc[['pov_level']]))     # value
    + ((int(crash_data19_t['east san gabriel'].loc[['pop_det_pov']])
     /int(crash_data19_t['san gabriel'].loc[['pop_det_pov']]))          #weight
    * int(crash_data19_t['east san gabriel'].loc[['pov_level']]))     # value
        ), decimals =2)

crash_data19_t

C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:12: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  (int(crash_data19_t['southwest san gabriel'].loc[['med_age']])),
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:13: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  (int(crash_data19_t['upper san gabriel'].loc[['med_age']])),
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:14: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  (int(crash_data19_t['east san gabriel'].loc[['med_age']]))])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:19: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  ((int(crash_data19_t['southwest san gabriel'].loc[['t_pop']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:20: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:22: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  + ((int(crash_data19_t['upper san gabriel'].loc[['t_pop']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:23: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:24: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  * int(crash_data19_t['upper san gabriel'].loc[['hs_g']]))     # value
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:25: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  + ((int(crash_data19_t['east san gabriel'].loc[['t_pop']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:26: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:27: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  * int(crash_data19_t['east san gabriel'].loc[['hs_g']]))     # value
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:32: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  ((int(crash_data19_t['southwest san gabriel'].loc[['t_pop']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:33: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:35: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  + ((int(crash_data19_t['upper san gabriel'].loc[['t_pop']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:36: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:37: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  * int(crash_data19_t['upper san gabriel'].loc[['lhs_g']]))     # value
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:38: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  + ((int(crash_data19_t['east san gabriel'].loc[['t_pop']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:39: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['san gabriel'].loc[['t_pop']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:40: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  * int(crash_data19_t['east san gabriel'].loc[['lhs_g']]))     # value
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:53: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  (int(crash_data19_t['southwest san gabriel'].loc[['med_inc']])),
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:54: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  (int(crash_data19_t['upper san gabriel'].loc[['med_inc']])),
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:55: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  (int(crash_data19_t['east san gabriel'].loc[['med_inc']]))])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:68: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  ((int(crash_data19_t['southwest san gabriel'].loc[['pop_det_pov']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:69: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['san gabriel'].loc[['pop_det_pov']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:71: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  + ((int(crash_data19_t['upper san gabriel'].loc[['pop_det_pov']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:72: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['san gabriel'].loc[['pop_det_pov']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:73: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  * int(crash_data19_t['upper san gabriel'].loc[['pov_level']]))     # value
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:74: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  + ((int(crash_data19_t['east san gabriel'].loc[['pop_det_pov']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:75: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['san gabriel'].loc[['pop_det_pov']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1652362312.py:76: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  * int(crash_data19_t['east san gabriel'].loc[['pov_level']]))     # value

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,east san gabriel,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,southwest san gabriel,torrance,upper san gabriel,whittier,unincorporated,long beach,pomona,glendale,alhambra,west hollywood,lancaster,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
t_pop,10098052.0,64932.0,351459.0,419001.0,958160.0,374562.0,577138.0,2598846.0,261333.0,192039.0,92404.0,274554.0,1860414.0,92078.0,215283.0,139773.0,497962.0,323808.0,146392.0,332369.0,325545.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1614337.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_age,36.2,45.1,33.1,35.8,36.9,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,40.9,41.7,39.5,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hs_g,20.7,11.7,25.8,24.7,23.8,24.1,18.9,18.0,18.2,30.2,12.7,13.2,20.7,8.3,25.0,9.3,24.3,25.3,16.0,22.1,28.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lhs_g,21.3,2.6,32.7,22.8,19.6,24.7,18.7,23.8,9.8,17.7,4.9,9.5,18.2,5.2,24.0,3.1,49.8,23.7,5.8,23.8,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_15,8238808.0,55178.0,276034.0,335208.0,782727.0,296679.0,467862.0,2155061.0,206153.0,147769.0,77071.0,228556.0,1538569.0,80689.0,164950.0,113921.0,380768.0,273833.0,121128.0,271261.0,265391.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1327821.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_inc,27856.0,51970.0,23818.0,27706.0,26877.0,25119.0,30587.0,26472.0,39705.0,30626.0,50473.0,40672.0,29234.0,54022.0,27095.0,63844.0,20407.0,23867.0,42808.0,26206.0,30132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26206.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_det_pov,9947799.0,61945.0,346675.0,415237.0,937341.0,372299.0,570151.0,2543269.0,253705.0,184377.0,91807.0,271572.0,1843478.0,91213.0,213877.0,139451.0,495905.0,320850.0,145494.0,329321.0,319832.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1587512.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pov_level,16.0,6.3,18.0,12.0,11.8,17.7,16.5,21.2,8.2,23.3,6.5,11.6,14.3,10.4,16.2,4.7,23.4,13.7,7.0,14.3,9.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,16.0,43.0,74.0,NaN,58.0,362.0,3215.0,25.0,NaN,1.0,75.0,90.0,84.0,NaN,147.0,41.0,NaN,47.0,NaN,30.0,394.0,331.0,84.0,78.0,57.0,56.0,51.0,43.0,42.0,42.0,37.0,35.0,35.0,33.0,32.0,31.0,31.0,31.0,30.0,29.0,27.0,27.0,26.0,26.0,25.0,25.0,24.0,24.0,21.0,20.0,19.0,19.0,18.0,15.00,14.0,13.0,12.0,12.0,12.0,12.0,11.0,11.0,10.0,10.0,10.0,9.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0

In [301]:
# Drop extra san gabriel columns 
crash_data19_t.drop(['southwest san gabriel', 'upper san gabriel', 
                'east san gabriel'], axis=1, inplace=True)

In [302]:
# Add additional counts to san gabriel
# + crash_data19_t['irwindale'].loc[['count']] Not counted in 2013 data
# # Combine into CCD designations -- san gabriel
crash_data19_t['san gabriel'].loc[['count']] = (
    crash_data19_t['alhambra'].loc[['count']] + crash_data19_t['arcadia'].loc[['count']]
    + crash_data19_t['baldwin park'].loc[['count']] + crash_data19_t['covina'].loc[['count']]
    + crash_data19_t['diamond bar'].loc[['count']] + crash_data19_t['duarte'].loc[['count']]
    + crash_data19_t['el monte'].loc[['count']] + crash_data19_t['industry'].loc[['count']]
    +  crash_data19_t['irwindale'].loc[['count']] + crash_data19_t['la puente'].loc[['count']]
    + crash_data19_t['la canada-flintridge'].loc[['count']] + crash_data19_t['monrovia'].loc[['count']]
    + crash_data19_t['montebello'].loc[['count']] + crash_data19_t['monterey park'].loc[['count']]
    + crash_data19_t['pomona'].loc[['count']] + crash_data19_t['rosemead'].loc[['count']]
    + crash_data19_t['san gabriel'].loc[['count']] + crash_data19_t['san marino'].loc[['count']]
    + crash_data19_t['sierra madre'].loc[['count']] + crash_data19_t['south el monte'].loc[['count']]
    + crash_data19_t['south pasadena'].loc[['count']] + crash_data19_t['temple city'].loc[['count']]
    + crash_data19_t['walnut'].loc[['count']] + crash_data19_t['west covina'].loc[['count']]
    )

crash_data19_t['san gabriel'].loc[['count']]

index
count    432.0
Name: san gabriel, dtype: float64

In [303]:
crash_data19_t

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,torrance,whittier,unincorporated,long beach,pomona,glendale,alhambra,west hollywood,lancaster,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
t_pop,10098052.0,64932.0,351459.0,419001.0,374562.0,577138.0,2598846.0,261333.0,192039.0,92404.0,274554.0,1860414.0,92078.0,215283.0,139773.0,497962.0,146392.0,325545.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1614337.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_age,36.2,45.1,33.1,35.8,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,41.7,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hs_g,20.7,11.7,25.8,24.7,24.1,18.9,18.0,18.2,30.2,12.7,13.2,20.7,8.3,25.0,9.3,24.3,16.0,28.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lhs_g,21.3,2.6,32.7,22.8,24.7,18.7,23.8,9.8,17.7,4.9,9.5,18.2,5.2,24.0,3.1,49.8,5.8,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_15,8238808.0,55178.0,276034.0,335208.0,296679.0,467862.0,2155061.0,206153.0,147769.0,77071.0,228556.0,1538569.0,80689.0,164950.0,113921.0,380768.0,121128.0,265391.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1327821.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_inc,27856.0,51970.0,23818.0,27706.0,25119.0,30587.0,26472.0,39705.0,30626.0,50473.0,40672.0,29234.0,54022.0,27095.0,63844.0,20407.0,42808.0,30132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26206.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_det_pov,9947799.0,61945.0,346675.0,415237.0,372299.0,570151.0,2543269.0,253705.0,184377.0,91807.0,271572.0,1843478.0,91213.0,213877.0,139451.0,495905.0,145494.0,319832.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1587512.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pov_level,16.0,6.3,18.0,12.0,17.7,16.5,21.2,8.2,23.3,6.5,11.6,14.3,10.4,16.2,4.7,23.4,7.0,9.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,16.0,43.0,74.0,58.0,362.0,3215.0,25.0,NaN,1.0,75.0,90.0,84.0,NaN,147.0,41.0,47.0,30.0,394.0,331.0,84.0,78.0,57.0,56.0,51.0,43.0,42.0,42.0,37.0,35.0,35.0,33.0,32.0,31.0,31.0,31.0,30.0,29.0,27.0,27.0,26.0,26.0,25.0,25.0,24.0,24.0,21.0,20.0,19.0,19.0,18.0,432.00,14.0,13.0,12.0,12.0,12.0,12.0,11.0,11.0,10.0,10.0,10.0,9.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0

In [304]:
# Create new column for antelope valley
crash_data19_t['antelope'] = np.nan
crash_data19_t

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,torrance,whittier,unincorporated,long beach,pomona,glendale,alhambra,west hollywood,lancaster,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre,antelope
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
t_pop,10098052.0,64932.0,351459.0,419001.0,374562.0,577138.0,2598846.0,261333.0,192039.0,92404.0,274554.0,1860414.0,92078.0,215283.0,139773.0,497962.0,146392.0,325545.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1614337.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_age,36.2,45.1,33.1,35.8,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,41.7,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hs_g,20.7,11.7,25.8,24.7,24.1,18.9,18.0,18.2,30.2,12.7,13.2,20.7,8.3,25.0,9.3,24.3,16.0,28.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lhs_g,21.3,2.6,32.7,22.8,24.7,18.7,23.8,9.8,17.7,4.9,9.5,18.2,5.2,24.0,3.1,49.8,5.8,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_15,8238808.0,55178.0,276034.0,335208.0,296679.0,467862.0,2155061.0,206153.0,147769.0,77071.0,228556.0,1538569.0,80689.0,164950.0,113921.0,380768.0,121128.0,265391.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1327821.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
med_inc,27856.0,51970.0,23818.0,27706.0,25119.0,30587.0,26472.0,39705.0,30626.0,50473.0,40672.0,29234.0,54022.0,27095.0,63844.0,20407.0,42808.0,30132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26206.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pop_det_pov,9947799.0,61945.0,346675.0,415237.0,372299.0,570151.0,2543269.0,253705.0,184377.0,91807.0,271572.0,1843478.0,91213.0,213877.0,139451.0,495905.0,145494.0,319832.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1587512.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pov_level,16.0,6.3,18.0,12.0,17.7,16.5,21.2,8.2,23.3,6.5,11.6,14.3,10.4,16.2,4.7,23.4,7.0,9.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,16.0,43.0,74.0,58.0,362.0,3215.0,25.0,NaN,1.0,75.0,90.0,84.0,NaN,147.0,41.0,47.0,30.0,394.0,331.0,84.0,78.0,57.0,56.0,51.0,43.0,42.0,42.0,37.0,35.0,35.0,33.0,32.0,31.0,31.0,31.0,30.0,29.0,27.0,27.0,26.0,26.0,25.0,25.0,24.0,24.0,21.0,20.0,19.0,19.0,18.0,432.00,14.0,13.0,12.0,12.0,12.0,12.0,11.0,11.0,10.0,10.0,10.0,9.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,NaN

In [307]:
# Combine north antelope and south antelope

# Total Population
crash_data19_t['antelope'].loc[['t_pop']] = (
    crash_data19_t['north antelope'].loc[['t_pop']]
    + crash_data19_t['south antelope'].loc[['t_pop']]
        )

# Median Age
crash_data19_t['antelope'].loc[['med_age']] = statistics.median([
(int(crash_data19_t['north antelope'].loc[['med_age']])),
(int(crash_data19_t['south antelope'].loc[['med_age']]))])
     

# Only High school graduation (percent of pop %)includes weights
crash_data19_t['antelope'].loc[['hs_g']] = np.round((
((int(crash_data19_t['north antelope'].loc[['t_pop']])
  /int(crash_data19_t['antelope'].loc[['t_pop']]))          #weight
    * crash_data19_t['north antelope'].loc[['hs_g']])  # value
    + ((int(crash_data19_t['south antelope'].loc[['t_pop']])
     /int(crash_data19_t['antelope'].loc[['t_pop']]))          #weight
    * int(crash_data19_t['south antelope'].loc[['hs_g']]))     # value
        ), decimals =2)

# Less than High school graduation (percent of pop %) includes weights
crash_data19_t['antelope'].loc[['lhs_g']] = np.round((
((int(crash_data19_t['north antelope'].loc[['t_pop']])
  /int(crash_data19_t['antelope'].loc[['t_pop']]))          #weight
    * crash_data19_t['north antelope'].loc[['lhs_g']])  # value
    + ((int(crash_data19_t['south antelope'].loc[['t_pop']])
     /int(crash_data19_t['antelope'].loc[['t_pop']]))          #weight
    * int(crash_data19_t['south antelope'].loc[['lhs_g']]))     # value
        ), decimals =2)

 
# Population Over 15
crash_data19_t['antelope'].loc[['pop_15']] = (
    crash_data19_t['north antelope'].loc[['pop_15']]
    + crash_data19_t['south antelope'].loc[['pop_15']]
        )
 
# Median Income
crash_data19_t['antelope'].loc[['med_inc']] = statistics.median([
(int(crash_data19_t['north antelope'].loc[['med_inc']])),
(int(crash_data19_t['south antelope'].loc[['med_inc']]))])
 

# Population Used to Determine Poverty
crash_data19_t['antelope'].loc[['pop_det_pov']] = (
    crash_data19_t['north antelope'].loc[['pop_det_pov']]
    + crash_data19_t['south antelope'].loc[['pop_det_pov']]
        )

# Percent of Population under Poverty Line (%) including weights
crash_data19_t['antelope'].loc[['pov_level']] = np.round((
((int(crash_data19_t['north antelope'].loc[['pop_det_pov']])
  /int(crash_data19_t['antelope'].loc[['pop_det_pov']]))          #weight
    * crash_data19_t['north antelope'].loc[['pov_level']])  # value
    + ((int(crash_data19_t['south antelope'].loc[['pop_det_pov']])
     /int(crash_data19_t['antelope'].loc[['pop_det_pov']]))          #weight
    * int(crash_data19_t['south antelope'].loc[['pov_level']]))     # value
        ), decimals =2)

crash_data19_t

C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:11: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  (int(crash_data19_t['north antelope'].loc[['med_age']])),
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:12: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  (int(crash_data19_t['south antelope'].loc[['med_age']]))])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:17: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  ((int(crash_data19_t['north antelope'].loc[['t_pop']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:18: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['antelope'].loc[['t_pop']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:20: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  + ((int(crash_data19_t['south antelope'].loc[['t_pop']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:21: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['antelope'].loc[['t_pop']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:22: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  * int(crash_data19_t['south antelope'].loc[['hs_g']]))     # value
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:27: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  ((int(crash_data19_t['north antelope'].loc[['t_pop']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:28: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['antelope'].loc[['t_pop']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:30: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  + ((int(crash_data19_t['south antelope'].loc[['t_pop']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:31: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['antelope'].loc[['t_pop']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:32: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  * int(crash_data19_t['south antelope'].loc[['lhs_g']]))     # value
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:44: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  (int(crash_data19_t['north antelope'].loc[['med_inc']])),
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:45: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  (int(crash_data19_t['south antelope'].loc[['med_inc']]))])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:56: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  ((int(crash_data19_t['north antelope'].loc[['pop_det_pov']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:57: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['antelope'].loc[['pop_det_pov']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:59: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  + ((int(crash_data19_t['south antelope'].loc[['pop_det_pov']])
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:60: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  /int(crash_data19_t['antelope'].loc[['pop_det_pov']]))          #weight
C:\Users\willi\AppData\Local\Temp\ipykernel_19200\2290293847.py:61: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  * int(crash_data19_t['south antelope'].loc[['pov_level']]))     # value

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,torrance,whittier,unincorporated,long beach,pomona,glendale,alhambra,west hollywood,lancaster,beverly hills,downey,el monte,culver city,palmdale,monterey park,south gate,norwalk,gardena,bellflower,lakewood,huntington park,west covina,carson,montebello,redondo beach,hawthorne,arcadia,santa clarita,baldwin park,bell,rosemead,lynwood,pico rivera,bell gardens,paramount,san gabriel,azusa,manhattan beach,malibu,el segundo,glendora,cerritos,claremont,cudahy,la mirada,covina,diamond bar,santa fe springs,hawaiian gardens,monrovia,signal hill,san dimas,commerce,la puente,la verne,south el monte,vernon,hermosa beach,lawndale,temple city,maywood,industry,artesia,calabasas,duarte,la canada-flintridge,agoura hills,south pasadena,irwindale,san marino,walnut,hidden hills,burbank,palos verdes est,sierra madre,antelope
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
t_pop,10098052.0,64932.0,351459.0,419001.0,374562.0,577138.0,2598846.0,261333.0,192039.0,92404.0,274554.0,1860414.0,92078.0,215283.0,139773.0,497962.0,146392.0,325545.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1614337.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,407322.00
med_age,36.2,45.1,33.1,35.8,35.0,35.1,34.9,36.6,33.8,47.9,40.7,37.7,39.9,33.7,40.7,31.0,41.7,36.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.00
hs_g,20.7,11.7,25.8,24.7,24.1,18.9,18.0,18.2,30.2,12.7,13.2,20.7,8.3,25.0,9.3,24.3,16.0,28.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.45
lhs_g,21.3,2.6,32.7,22.8,24.7,18.7,23.8,9.8,17.7,4.9,9.5,18.2,5.2,24.0,3.1,49.8,5.8,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.03
pop_15,8238808.0,55178.0,276034.0,335208.0,296679.0,467862.0,2155061.0,206153.0,147769.0,77071.0,228556.0,1538569.0,80689.0,164950.0,113921.0,380768.0,121128.0,265391.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1327821.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,312719.00
med_inc,27856.0,51970.0,23818.0,27706.0,25119.0,30587.0,26472.0,39705.0,30626.0,50473.0,40672.0,29234.0,54022.0,27095.0,63844.0,20407.0,42808.0,30132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26206.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28860.50
pop_det_pov,9947799.0,61945.0,346675.0,415237.0,372299.0,570151.0,2543269.0,253705.0,184377.0,91807.0,271572.0,1843478.0,91213.0,213877.0,139451.0,495905.0,145494.0,319832.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1587512.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,398254.00
pov_level,16.0,6.3,18.0,12.0,17.7,16.5,21.2,8.2,23.3,6.5,11.6,14.3,10.4,16.2,4.7,23.4,7.0,9.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.38
count,NaN,16.0,43.0,74.0,58.0,362.0,3215.0,25.0,NaN,1.0,75.0,90.0,84.0,NaN,147.0,41.0,47.0,30.0,394.0,331.0,84.0,78.0,57.0,56.0,51.0,43.0,42.0,42.0,37.0,35.0,35.0,33.0,32.0,31.0,31.0,31.0,30.0,29.0,27.0,27.0,26.0,26.0,25.0,25.0,24.0,24.0,21.0,20.0,19.0,19.0,18.0,432.00,14.0,13.0,12.0,12.0,12.0,12.0,11.0,11.0,10.0,10.0,10.0,9.0,8.0,8.0,8.0,8.0,8.0,7.0,7.0,6.0,6.0,6.0,6.0,6.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,NaN

In [308]:
# Drop extra antelope columns 
crash_data19_t.drop(['north antelope', 'south antelope', 
               ], axis=1, inplace=True)

In [309]:
# Add additional counts to antelope valley
# # Combine into CCD designations -- antelope valley
crash_data19_t['antelope'].loc[['count']] = (
    crash_data19_t['lancaster'].loc[['count']] + crash_data19_t['palmdale'].loc[['count']]
    )

crash_data19_t['antelope'].loc[['count']]

index
count    86.0
Name: antelope, dtype: float64

In [246]:
# # Turn into percentages

# crash_data19_t.loc[['hs_g']] = (crash_data19_t.loc[['hs_g']] / 100)
# crash_data19_t.loc[['lhs_g']] = (crash_data19_t.loc[['lhs_g']] / 100)
# crash_data19_t.loc[['pov_level']] = (crash_data19_t.loc[['pov_level']] / 100)
# crash_data19_t

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,east san gabriel,inglewood,long beach-lakewood,los angeles,newhall,north antelope,palos verdes,pasadena,san fernando,santa monica,south antelope,south bay cities,south gate-east los angeles,southwest san gabriel,torrance,upper san gabriel,whittier,unincorporated,long beach,glendale,pomona,lancaster,west hollywood,downey,monterey park,santa clarita,el monte,south gate,beverly hills,hawthorne,alhambra,huntington park,palmdale,lakewood,norwalk,redondo beach,lynwood,bellflower,west covina,bell gardens,gardena,carson,culver city,baldwin park,paramount,arcadia,rosemead,la mirada,montebello,san gabriel,bell,santa fe springs,azusa,pico rivera,malibu,monrovia,hermosa beach,covina,lawndale,signal hill,industry,cudahy,claremont,cerritos,glendora,vernon,south pasadena,agoura hills,temple city,commerce,la canada-flintridge,south el monte,manhattan beach,maywood,hawaiian gardens,la puente,san dimas,diamond bar,artesia,el segundo,burbank,la verne,san marino,sierra madre,walnut,irwindale,duarte,avalon,westlake village,palos verdes est,rancho palos verdes,calabasas
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
hs_g,0.207,0.117,0.258,0.247,0.238,0.241,0.189,0.18,0.182,0.302,0.127,0.132,0.207,0.083,0.25,0.093,0.243,0.253,0.16,0.221,0.286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [218]:
crash_data19_t.columns

Index(['los angeles county, california', 'agoura hills-malibu', 'compton',
       'downey-norwalk', 'inglewood', 'long beach-lakewood', 'los angeles',
       'newhall', 'palos verdes', 'pasadena', 'san fernando', 'santa monica',
       'south bay cities', 'south gate-east los angeles', 'torrance',
       'whittier', 'los angeles-long beach-anaheim, ca metro area',
       'unincorporated', 'long beach', 'pomona', 'glendale', 'lancaster',
       'west hollywood', 'hawthorne', 'south gate', 'santa clarita', 'lynwood',
       'palmdale', 'alhambra', 'monterey park', 'redondo beach', 'norwalk',
       'huntington park', 'downey', 'el monte', 'lakewood', 'bellflower',
       'arcadia', 'covina', 'azusa', 'montebello', 'bell gardens', 'rosemead',
       'west covina', 'gardena', 'carson', 'culver city', 'san gabriel',
       'baldwin park', 'monrovia', 'bell', 'manhattan beach', 'la puente',
       'glendora', 'claremont', 'paramount', 'beverly hills', 'cerritos',
       'pico rivera', 'lawndale', 'hermosa beach', 'temple city',
       'santa fe springs', 'industry', 'diamond bar', 'south pasadena',
       'san dimas', 'south el monte', 'la mirada', 'maywood', 'malibu',
       'el segundo', 'la verne', 'commerce', 'vernon', 'signal hill',
       'irwindale', 'san marino', 'calabasas', 'artesia', 'walnut', 'burbank',
       'cudahy', 'la canada-flintridge', 'duarte', 'hawaiian gardens',
       'sierra madre', 'agoura hills', 'antelope'],
      dtype='object')

In [310]:
# Reframe the dataset for download, delete excess columns
crash_data19_t = crash_data19_t[['los angeles county, california', 'agoura hills-malibu', 'compton',
       'downey-norwalk', 'inglewood', 'long beach-lakewood', 'los angeles',
       'newhall', 'palos verdes', 'pasadena', 'san fernando', 'santa monica',
       'south bay cities', 'south gate-east los angeles', 'torrance',
       'whittier', 'san gabriel', 'antelope']]

# Rename label for clarity
crash_data19_t.rename(index={'count': 'p_crash'}, inplace = True)
crash_data19_t

C:\Users\willi\AppData\Local\Temp\ipykernel_19200\1169833593.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crash_data19_t.rename(index={'count': 'p_crash'}, inplace = True)

,"los angeles county, california",agoura hills-malibu,compton,downey-norwalk,inglewood,long beach-lakewood,los angeles,newhall,palos verdes,pasadena,san fernando,santa monica,south bay cities,south gate-east los angeles,torrance,whittier,san gabriel,antelope
index,,,,,,,,,,,,,,,,,,
t_pop,10098052.0,64932.0,351459.0,419001.0,374562.0,577138.0,2598846.0,261333.0,92404.0,274554.0,1860414.0,92078.0,139773.0,497962.0,146392.0,325545.0,1614337.00,407322.00
med_age,36.2,45.1,33.1,35.8,35.0,35.1,34.9,36.6,47.9,40.7,37.7,39.9,40.7,31.0,41.7,36.9,39.00,33.00
hs_g,20.7,11.7,25.8,24.7,24.1,18.9,18.0,18.2,12.7,13.2,20.7,8.3,9.3,24.3,16.0,28.6,23.26,27.45
lhs_g,21.3,2.6,32.7,22.8,24.7,18.7,23.8,9.8,4.9,9.5,18.2,5.2,3.1,49.8,5.8,18.6,20.77,21.03
pop_15,8238808.0,55178.0,276034.0,335208.0,296679.0,467862.0,2155061.0,206153.0,77071.0,228556.0,1538569.0,80689.0,113921.0,380768.0,121128.0,265391.0,1327821.00,312719.00
med_inc,27856.0,51970.0,23818.0,27706.0,25119.0,30587.0,26472.0,39705.0,50473.0,40672.0,29234.0,54022.0,63844.0,20407.0,42808.0,30132.0,26206.00,28860.50
pop_det_pov,9947799.0,61945.0,346675.0,415237.0,372299.0,570151.0,2543269.0,253705.0,91807.0,271572.0,1843478.0,91213.0,139451.0,495905.0,145494.0,319832.0,1587512.00,398254.00
pov_level,16.0,6.3,18.0,12.0,17.7,16.5,21.2,8.2,6.5,11.6,14.3,10.4,4.7,23.4,7.0,9.9,12.17,19.38
p_crash,NaN,16.0,43.0,74.0,58.0,362.0,3215.0,25.0,1.0,75.0,90.0,84.0,147.0,41.0,47.0,30.0,432.00,86.00

In [167]:
# Convert to CSV 2019

# crash_data19_t.to_csv('crash_data19_t.csv')

In [311]:
# Convert to CSV 2017

crash_data19_t.to_csv('crash_data18_t.csv')

In [110]:
crash_data19_t.index

Index(['t_pop', 'med_age', 'hs_g', 'lhs_g', 'pop_15', 'med_inc', 'pop_det_pov',
       'pov_level', 'p_crash'],
      dtype='object', name='index')

## Repeat for Year